services:
  backend:
    build:
      context: ./BackendAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=tcp:serverklas1groep2.database.windows.net,1433;Initial Catalog=dbKlas1Groep2_2026-01-14T15-46Z;Persist Security Info=False;User ID=VeilingKlokKlas1Groep2;Password=Groep2Klas1!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    ports:
      - "5219:5219"

  frontend:
    build:
      context: ./FrontendWeb
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
