// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeilingKlok.Data;

#nullable disable

namespace VeilingKlokKlas1Groep2.Migrations
{
    [DbContext(typeof(VeilingKlokContext))]
    [Migration("20251014124635_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeilingKlok.Models.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("VeilingKlok.Models.Domain.Koper", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_code");

                    b.Property<string>("Regio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("regio");

                    b.HasKey("AccountId");

                    b.ToTable("Koper");
                });

            modelBuilder.Entity("VeilingKlok.Models.Domain.Kweker", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Adress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adress");

                    b.Property<string>("KvkNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kvk_nmr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Regio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("regio");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("AccountId");

                    b.ToTable("Kweker");
                });

            modelBuilder.Entity("VeilingKlok.Models.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BoughtAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("bought_at");

                    b.Property<int>("KoperId")
                        .HasColumnType("int")
                        .HasColumnName("koper_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("KoperId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("VeilingKlok.Models.Domain.Koper", b =>
                {
                    b.HasOne("VeilingKlok.Models.Domain.Account", "Account")
                        .WithOne("Koper")
                        .HasForeignKey("VeilingKlok.Models.Domain.Koper", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("VeilingKlok.Models.Domain.Kweker", b =>
                {
                    b.HasOne("VeilingKlok.Models.Domain.Account", "Account")
                        .WithOne("Kweker")
                        .HasForeignKey("VeilingKlok.Models.Domain.Kweker", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("VeilingKlok.Models.Domain.Order", b =>
                {
                    b.HasOne("VeilingKlok.Models.Domain.Koper", "Koper")
                        .WithMany("Orders")
                        .HasForeignKey("KoperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koper");
                });

            modelBuilder.Entity("VeilingKlok.Models.Domain.Account", b =>
                {
                    b.Navigation("Koper")
                        .IsRequired();

                    b.Navigation("Kweker")
                        .IsRequired();
                });

            modelBuilder.Entity("VeilingKlok.Models.Domain.Koper", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
