// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeilingKlokApp.Data;

#nullable disable

namespace VeilingKlokKlas1Groep2.Migrations
{
    [DbContext(typeof(VeilingKlokContext))]
    partial class VeilingKlokContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Regio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("regio");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BoughtAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("bought_at");

                    b.Property<int>("KoperId")
                        .HasColumnType("int")
                        .HasColumnName("koper_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("KoperId");

                    b.HasIndex("ProductId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<int>("KwekerId")
                        .HasColumnType("int")
                        .HasColumnName("kweker_id");

                    b.Property<decimal>("MinimumPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("minimum_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.HasIndex("KwekerId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.VeilingKlok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_in_seconds");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int>("LiveViews")
                        .HasColumnType("int")
                        .HasColumnName("live_views");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("naam");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<int>("VeilingmeesterId")
                        .HasColumnType("int")
                        .HasColumnName("veilingmeester_id");

                    b.HasKey("Id");

                    b.HasIndex("VeilingmeesterId");

                    b.ToTable("Veilingklok");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Koper", b =>
                {
                    b.HasBaseType("VeilingKlokApp.Models.Domain.Account");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_code");

                    b.ToTable("Koper");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Kweker", b =>
                {
                    b.HasBaseType("VeilingKlokApp.Models.Domain.Account");

                    b.Property<string>("Adress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adress");

                    b.Property<string>("KvkNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kvk_nmr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telephone");

                    b.ToTable("Kweker");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Veilingmeester", b =>
                {
                    b.HasBaseType("VeilingKlokApp.Models.Domain.Account");

                    b.Property<int>("AurthorisatieCode")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("soort_veiling");

                    b.ToTable("Veilingmeester");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Order", b =>
                {
                    b.HasOne("VeilingKlokApp.Models.Domain.Koper", "Koper")
                        .WithMany("Orders")
                        .HasForeignKey("KoperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeilingKlokApp.Models.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koper");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Product", b =>
                {
                    b.HasOne("VeilingKlokApp.Models.Domain.Kweker", "Kweker")
                        .WithMany("Products")
                        .HasForeignKey("KwekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kweker");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.RefreshToken", b =>
                {
                    b.HasOne("VeilingKlokApp.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.VeilingKlok", b =>
                {
                    b.HasOne("VeilingKlokApp.Models.Domain.Veilingmeester", "Veilingmeester")
                        .WithMany("Veilingklokken")
                        .HasForeignKey("VeilingmeesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veilingmeester");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Koper", b =>
                {
                    b.HasOne("VeilingKlokApp.Models.Domain.Account", null)
                        .WithOne()
                        .HasForeignKey("VeilingKlokApp.Models.Domain.Koper", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Kweker", b =>
                {
                    b.HasOne("VeilingKlokApp.Models.Domain.Account", null)
                        .WithOne()
                        .HasForeignKey("VeilingKlokApp.Models.Domain.Kweker", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Veilingmeester", b =>
                {
                    b.HasOne("VeilingKlokApp.Models.Domain.Account", null)
                        .WithOne()
                        .HasForeignKey("VeilingKlokApp.Models.Domain.Veilingmeester", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Koper", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Kweker", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VeilingKlokApp.Models.Domain.Veilingmeester", b =>
                {
                    b.Navigation("Veilingklokken");
                });
#pragma warning restore 612, 618
        }
    }
}
