import i18n from 'i18next';
import { initReactI18next, useTranslation } from 'react-i18next';

export const resources = {
	nl: {
		translation: {
			// General texts
			welcome: 'Welcome',
			language: 'Taal',
			services: 'Diensten',

			// App Objects
			veilingklok: 'Veilingklok',
			growers: 'Kwekers',
			buyer: 'Kopers',
			flowers: 'Bloemen',
			transactions: 'Transacties',
			dashboard: 'Dashboard',
			settings: 'Instellingen',
			orders: 'Orders',
			products: 'Producten',
			back: 'Terug',
			manage_account: 'Account beheren',
			my_orders: 'Mijn bestellingen',
			browse_flowers: 'Bloemen bekijken',
			auctions: 'Veilingen',
			manage_auction: 'Veilingbeheren',
			region_flowers: 'Regio bloemen',

			// Dictionary terms
			welcome_back: 'Welkom terug',
			this_month: 'Deze maand',
			select_region: 'Selecteer regio',
			stock: 'Voorraad',
			status: 'Status',
			items: 'Artikelen',
			is: 'is',
			step: 'Stap',
			of: 'van',
			close: 'Sluiten',
			go_back_home: 'Ga terug naar home',
			previous: 'Vorige',
			next: 'Volgende',
			added: 'Toegevoegd',
			for: 'voor',
			date: 'Datum',
			seconds: 'seconden',
			total: 'Totaal',
			open: 'Open',
			scheduled: 'Ingepland',
			started: 'Gestart',
			paused: 'Gepauzeerd',
			stopped: 'Gestopt',
			ended: 'Beëindigd',
			Processing: 'In behandeling',
			processing: 'In behandeling',
			processed: 'Verwerkt',
			delivered: 'Geleverd',
			cancelled: 'Geannuleerd',
			returned: 'Geretourneerd',
			something_went_wrong: 'Something went wrong.',
			unexpected_happened: 'An unexpected error occurred. Please try again later.',

			// Account types
			Koper: 'Koper',
			Kweker: 'Kweker',
			Veilingmeester: 'Veilingmeester',

			// Auth State messages
			login: 'Inloggen',
			get_Started: 'Meld je aan',
			logout: 'Uitloggen',
			logging_in: 'Logging in...',
			logged_in: 'Logged in successfully',
			logging_out: 'Logging out...',
			creating_account: 'Creating account...',
			account_created: 'Account created successfully',
			account_created_error: 'Account creation failed',
			account_created_error_message: 'An error occurred while creating your account. Please try again later.',
			account_created_error_message_technical: 'An error occurred while creating your account. Please contact support.',
			account_created_error_message_technical_technical: 'An error occurred while creating your account. Please contact support.',

			//Login and register page texts
			login_title: 'Log in',
			sign_in_message: 'Meld u alstublieft aan bij uw account',
			forgot_password: 'Wachtwoord vergeten?',
			create_account: 'Account aanmaken',
			password: 'Wachtwoord',
			email: 'E-mailadres',
			address: 'Adres',
			postcode: 'Postcode',
			region: 'Regio',
			company_name: 'Bedrijfsnaam',
			kvk_number: 'KVK-Nummer',
			phonenumber: 'Telefoonnummer',
			authorisation_code: 'Autorisatiecode',
			country: 'Land',
			first_name: 'Voornaam',
			last_name: 'Achternaam',

			// Home page Texts
			what_is_flori_clock: 'Wat is FloriClock?',
			what_is_flori_clock_description: 'FloriClock is een digitaal veilingplatform dat kwekers en bloemisten samenbrengt om bloemen en planten efficiënt te verhandelen. Ons doel is om de veilinghandel in bloemen en planten te vereenvoudigen en te optimaliseren door middel van een gebruiksvriendelijke online marktplaats.',
			how_it_works: 'Hoe werkt het?',
			flower_types: 'Bloemsoorten',
			flower_types_description: 'Ontdek een breed scala aan bloemsoorten die beschikbaar zijn op ons platform. Van rozen tot tulpen, vind precies wat je zoekt.',
			contact_us: 'Contacteer ons',
			welcome_title: 'Welkom bij FloriClock',
			welcome_description: `Bloemen en planten verkopen en kopen vanop nu nog makkelijker met FloriClock!
			Een innovatief platform dat kwekers en bloemisten samenbrengt om bloemen en planten efficiënt te verhandelen.`,
			welcome_cta_text: `Begin vandaag nog met het ontdekken van ons platform. Meld je aan of log in om toegang te krijgen tot onze diensten.`,
			flowers_description: 'Verschillende bloemsoorten',
			growers_description: 'Groot aantal kwekers aangesloten',
			transactions_description: 'Succesvolle transacties dagelijks',
			what_do_growers: 'Plaatsen van hun producten en beheren van hun aanbod',
			veilingmeesters: 'Veilingmeesters',
			what_do_veilingmeesters: 'Beheren van veilingen en zorgen voor een vlotte afhandeling',
			what_do_buyer: 'Zoeken en bieden op bloemen en planten van hun keuze',
			what_is_veilingklok: 'Een geavanceerd systeem dat de tijd en volgorde van biedingen regelt tijdens veilingen',

			// Koper Dashboard texts
			koper_dashboard: 'Mijn Dashboard',
			koper_dashboard_sub: 'Overzicht van je profiel en acties',
			koper_supplier: 'Aanvoerder',
			koper_avr: 'avr nr',
			koper_country: 'land',
			koper_stems_per_bundle: 'aantal stelen per bos',
			koper_stock: 'Voorraad: {{count}} stuks',
			koper_qty_input_aria: 'Aantal te kopen stelen',
			koper_buy: 'Koop product',
			koper_max_stock: 'Max voorraad',
			koper_bundle_label: 'bos',
			koper_footer_about_title: 'Over FloriClock',
			koper_footer_about_line1: 'Digitale veiling voor bloemen en planten.',
			koper_footer_about_line2: 'Gebouwd door studenten - demo omgeving.',
			koper_footer_product_title: 'Product',
			koper_footer_live: 'Live veiling',
			koper_footer_history: 'Prijsgeschiedenis',
			koper_footer_favorites: 'Favorieten',
			koper_footer_resources_title: 'Resources',
			koper_footer_docs: 'Documentatie',
			koper_footer_faq: 'Veelgestelde vragen',
			koper_footer_status: 'Status',
			koper_footer_contact_title: 'Contact',
			koper_footer_support: 'Service & support',
			koper_footer_form: 'Contactformulier',
			koper_footer_locations: 'Locaties',
			refresh: 'Vernieuwen',
			no_products_available: 'Geen producten beschikbaar',
			koper_product_image_alt: 'Productafbeelding',
			koper_upcoming_meta: '{{company}} - {{dimension}}',
			koper_upcoming_badge: 'A1',

			// Kweker dashboard texts
			kweker_welcome: 'Welkom, {{firstName}} {{lastName}}!',
			kweker_desc: 'Welkom op de dashboard pagina! Bekijk hier uw producten!',
			kweker_section_products: 'Producten',
			kweker_table_product_label: 'Product',
			kweker_table_stock_label: 'Voorraad',
			kweker_table_price_label: 'Prijs',
			kweker_table_action_label: 'Actie',
			kweker_table_action_view: 'Bekijk',
			kweker_table_action_view_aria: 'Bekijk product {{name}}',
			kweker_add_product_button: 'Voeg nieuw product toe',
			kweker_add_product_button_aria: 'Knop om nieuw product toe te voegen',
			kweker_add_product_modal_title: 'Nieuw product toevoegen',
			kweker_modal_close_aria: 'Sluiten',
			kweker_form_name_label: 'Naam',
			kweker_form_name_required: 'Naam is verplicht',
			kweker_form_description_label: 'Beschrijving',
			kweker_form_description_required: 'Beschrijving is verplicht',
			kweker_form_min_price_label: 'Minimum prijs (EUR)',
			kweker_form_min_price_required: 'Minimum prijs is verplicht',
			kweker_form_stock_label: 'Aantal',
			kweker_form_stock_required: 'Aantal is verplicht',
			kweker_form_image_label: 'Afbeelding (Base64)',
			kweker_form_dimension_label: 'Maat',
			kweker_form_submit_busy: 'Bezig...',
			kweker_form_submit: 'Voeg nieuw product toe',
			kweker_form_cancel: 'Annuleren',
			kweker_form_create_error: 'Onbekende fout bij het aanmaken van product',
			kweker_preview_title: 'Product',
			kweker_preview_loading: 'Bezig met laden...',
			kweker_preview_error: 'Kon het product niet laden.',
			kweker_preview_stock: 'Voorraad: {{count}}',
			kweker_preview_size: 'Maat: {{dimension}}',
			kweker_preview_grower: 'Kweker: {{company}}',

			// Kweker stats texts
			kweker_stats_offered: 'Producten aangeboden',
			kweker_stats_sold: 'Producten verkocht',
			kweker_stats_total_revenue: 'Totale omzet',
			kweker_stats_stems_sold: 'Bloemstelen verkocht',
			kweker_stats_offered_value: '1,500 EUR',
			kweker_stats_sold_value: '50',
			kweker_stats_total_revenue_value: '1,500 EUR',
			kweker_stats_stems_sold_value: '1,000',
			kweker_stats_change: '+0.00%',
			kweker_stats_this_month: 'Deze maand',

			// Veilingmeester dashboard texts
			vm_title: 'Veilingmeester',
			vm_tab_auction: 'Veiling',
			vm_tab_history: 'History',
			vm_section_subtitle: 'Beheer de veiling en volg de producten.',
			vm_button_open_auction: 'Open veiling',
			vm_button_end_auction: 'Eindig veiling',
			vm_button_start_auction: 'Start veiling',
			vm_alert_no_products: 'Er zijn geen producten om te veilen.',
			vm_alert_open_failed: 'Openen van veiling mislukt (zie console)',
			vm_alert_min_price_invalid: 'Vul eerst een geldige minimumprijs in.',
			vm_queue_load_error: 'Producten ophalen mislukt.',
			vm_empty_no_products: 'Geen producten beschikbaar.',
			vm_clock_placeholder: 'Klok',
			vm_label_duration_seconds: 'Duur (seconden)',
			vm_label_min_price: 'Minimumprijs (veilingmeester)',
			vm_section_other_products: 'Overige producten',
			vm_loading_products: 'Producten laden...',
			vm_stock_label: 'Voorraad',
			vm_stock_value: 'Voorraad: {{count}}',
			vm_max_price_label: 'Maximumprijs (kweker)',
			vm_price_not_set: 'Nog niet gezet',
			vm_history_empty: 'Nog geen veilinghistorie beschikbaar.',
			vm_history_loading: 'Veilinghistorie laden...',
			vm_history_load_error: 'Kon veilinghistorie niet laden.',
			vm_history_unknown_date: 'Onbekende datum',
			vm_history_total_revenue_label: 'Totale omzet',
			vm_history_start_label: 'Start',
			vm_history_end_label: 'Einde',
			vm_history_products_label: 'Producten',
			vm_history_revenue_label: 'Omzet',
			vm_history_sold_products_title: 'Verkochte producten',
			vm_history_unknown_buyer: 'Onbekende koper',
			vm_history_piece_count: '{{count}} stuks',
			vm_history_products_count: '{{count}} producten',
			vm_history_auction_title: 'Veiling {{date}}',
			vm_demo_buyer: 'Demo koper',

			// Veilingmeester aria labels
			vm_tab_auction_aria: 'Tabblad veiling',
			vm_tab_history_aria: 'Tabblad historie',
			vm_button_open_auction_aria: 'Knop om veiling te openen',
			vm_button_end_auction_aria: 'Knop om veiling te eindigen',
			vm_button_start_auction_aria: 'Knop om veiling te starten',
			vm_input_duration_aria: 'Invoerveld voor veilingduur in seconden',
			vm_input_min_price_aria: 'Invoerveld voor minimumprijs',
			vm_history_summary_aria: 'Toon details voor veiling op {{date}}',
			vm_queue_name_1: 'Rode Rozen Premium',
			vm_queue_desc_1: 'Dieprode rozen van topkwaliteit',
			vm_queue_company_1: 'Kwekerij Bloemenhof',
			vm_queue_name_2: 'Witte Lelies',
			vm_queue_desc_2: 'Verse witte lelies, grote knoppen',
			vm_queue_company_2: 'Lelie Centrum BV',
			vm_queue_name_3: 'Zonnebloem XL',
			vm_queue_desc_3: 'Grote zonnebloemen met stevige stelen',
			vm_queue_company_3: 'Zon & Co',
			vm_queue_name_4: 'Tulpen Mix',
			vm_queue_desc_4: 'Mix van voorjaarskleuren, premium selectie',
			vm_queue_company_4: 'Tulipa Holland',
			vm_queue_name_5: 'Orchidee Phalaenopsis',
			vm_queue_desc_5: 'Bloeiend en rijk vertakt',
			vm_queue_company_5: 'Orchid World',

			// Veilingmeester Texts
			veilingklok_created: 'Veilingklok succesvol aangemaakt',
			veilingklok_removing_product: 'Product verwijderen van veilingklok...',
			veilingklok_product_removed: 'Product succesvol verwijderd van veilingklok',
			veilingklok_product_remove_error: 'Fout bij het verwijderen van product van veilingklok',
			veilingklok_adding_product: 'Product toevoegen aan veilingklok...',
			veilingklok_product_added: 'Product succesvol toegevoegd aan veilingklok',
			veilingklok_product_add_error: 'Fout bij het toevoegen van product aan veilingklok',
			veilingklok_loading: 'Veilingklokken laden...',
			veilingklok_loaded: 'Veilingklokken succesvol geladen',
			veilingklok_load_error: 'Fout bij het laden van veilingklokken',

			update_auction_clock: 'Veilingklok bijwerken',
			create_auction_clock: 'Veilingklok aanmaken',
			auction_clock_details: 'Veilingklok details',
			total_estimated_value: 'Totaal geschatte waarde',
			no_veilingen_planned: 'Geen veilingen gepland',
			veilingklok_status: 'Veilingklok status',
			scheduledDate: 'Geplande datum',
			totalProducts: 'Totaal producten',
			totalBids: 'Totaal biedingen',
			endedDate: 'Einddatum',
			amount_viewed: 'Aantal bekeken',
			duration_per_bids: 'Duur per bod (seconden)',
			recent_auctionclocks: 'Recente veilingklokken',
			scheduled_for_auction: 'Gepland voor veiling',
			no_veiling_planned: 'Geen veiling gepland',
			set_auction_product_price: 'Stel veilingproductprijs in',
			product_veiling_start_price: 'Veiling startprijs',
			schedule_veilingklok: 'Veilingklok plannen',
			auction_products: 'Veilingklok producten',
			manage_auction_clock: 'Veilingklok beheren',
			manage_product_price_txt: 'Hier kunt u de prijzen van producten beheren die beschikbaar zijn in uw regio.',
			manage_auction_txt: 'Hier kunt u de veilingen beheren die u heeft gepland voor uw regio.',
			manage_veiling_klok_txt: 'Hier kunt u de veilingklokken beheren die u heeft gepland voor uw regio.',
			manage_veiling_klok: 'Veilingklok beheren',
			start_veiling_klok: 'Start Veilingklok',
			stop_veiling_klok: 'Stop Veilingklok',
			pause_veiling_klok: 'Pause Veilingklok',
			resume_veiling_klok: 'Hervat Veilingklok',
			live_views: 'Live weergaven',
			updating_veilingklok: 'Veilingklok bijwerken...',
			veilingklok_updated: 'Veilingklok succesvol bijgewerkt',
			veilingklok_update_error: 'Fout bij het bijwerken van veilingklok',
			starting_product_veiling: 'Veiling van product starten...',
			product_veiling_started: 'Veiling van product succesvol gestart',
			product_veiling_start_error: 'Fout bij het starten van de veiling van het product',
			// Header and Footer texts
			dashboard: 'Dashboard',
			manage_account: 'Account beheren',
			settings: 'Instellingen',
			settings_account: 'Account',
			settings_privacy: 'Privacy',
			settings_notifications: 'Meldingen',
			settings_preferences: 'Voorkeuren',
			settings_preferences_title: 'Voorkeuren',
			settings_preferences_subtitle: 'Pas thema en taal aan voor je account.',
			settings_theme_label: 'Weergavemodus',
			settings_theme_aria: 'Schakel tussen licht en donker thema',
			settings_theme_dark: 'Donkere modus',
			settings_theme_light: 'Lichte modus',
			settings_language_label: 'Taal',
			settings_account_aria: 'Tabblad account',
			settings_privacy_aria: 'Tabblad privacy',
			settings_notifications_aria: 'Tabblad meldingen',
			settings_preferences_aria: 'Tabblad voorkeuren',
			settings_back_to_dashboard: 'Terug naar dashboard',
			settings_back_to_dashboard_aria: 'Knop om terug naar dashboard te gaan',

			// Language labels
			language_dutch: 'Nederlands',
			language_english: 'English',
			language_french: 'Francais',
			language_spanish: 'Espanol',
			language_german: 'Deutsch',

			// Account settings texts
			account_settings_title: 'Account',
			account_settings_subtitle: 'Werk je profielgegevens en wachtwoord bij.',
			account_notice_not_ready: 'Accountgegevens zijn nog niet beschikbaar.',
			account_notice_saving: 'Wijzigingen opslaan...',
			account_notice_required: 'Vul alle verplichte velden in.',
			account_notice_complete_address: 'Vul het volledige adres in.',
			account_notice_no_changes: 'Geen wijzigingen om op te slaan.',
			account_notice_updated: 'Account succesvol bijgewerkt.',
			account_notice_error: 'Er is iets misgegaan bij het opslaan.',
			account_company_name_label: 'Bedrijfsnaam',
			account_company_name_placeholder: 'Bedrijfsnaam',
			account_edit_company_name_aria: 'Bedrijfsnaam bewerken',
			account_first_name_label: 'Voornaam',
			account_first_name_placeholder: 'Voornaam',
			account_last_name_label: 'Achternaam',
			account_last_name_placeholder: 'Achternaam',
			account_email_label: 'E-mailadres',
			account_email_placeholder: 'naam@example.com',
			account_edit_email_aria: 'E-mailadres bewerken',
			account_phone_label: 'Telefoonnummer',
			account_phone_placeholder: '+31 6 12345678',
			account_edit_phone_aria: 'Telefoonnummer bewerken',
			account_region_label: 'Regio',
			account_region_placeholder: 'Noord-Holland',
			account_edit_region_aria: 'Regio bewerken',
			account_address_show: 'Adres wijzigen',
			account_address_hide: 'Verberg adres',
			account_street_label: 'Straat',
			account_street_placeholder: 'Straat',
			account_edit_street_aria: 'Adres bewerken',
			account_city_label: 'Plaats',
			account_city_placeholder: 'Plaats',
			account_edit_city_aria: 'Plaats bewerken',
			account_region_state_label: 'Regio',
			account_region_state_placeholder: 'Regio',
			account_edit_region_state_aria: 'Regio bewerken',
			account_postal_code_label: 'Postcode',
			account_postal_code_placeholder: 'Postcode',
			account_edit_postal_aria: 'Postcode bewerken',
			account_country_label: 'Land',
			account_country_placeholder: 'Land',
			account_edit_country_aria: 'Land bewerken',
			account_password_required: 'Wachtwoord (verplicht)',
			account_password_new: 'Nieuw wachtwoord',
			account_password_placeholder: '********',
			account_password_placeholder_locked: 'Klik om wachtwoord te wijzigen',
			account_password_hide: 'Verbergen',
			account_password_show: 'Tonen',
			account_password_cancel_change: 'Wachtwoord wijzigen annuleren',
			account_password_change: 'Wachtwoord wijzigen',
			account_save_busy: 'Opslaan...',
			account_save: 'Wijzigingen opslaan',
			account_save_aria: 'Knop om wijzigingen op te slaan',

			// Privacy settings texts
			privacy_title: 'Privacy',
			privacy_subtitle: 'Beheer hoe je profiel en activiteit worden gedeeld.',
			privacy_toggle_profile: 'Toon mijn profiel aan andere gebruikers',
			privacy_toggle_search: 'Sta zoekmachines toe mijn profiel te indexeren',
			privacy_toggle_status: 'Deel activiteitsstatus',
			privacy_save: 'Privacy bijwerken',

			// Notifications settings texts
			notifications_title: 'Meldingen',
			notifications_subtitle: 'Kies hoe je updates wilt ontvangen.',
			notifications_email_updates: 'Stuur e-mail over veilingupdates',
			notifications_sms_bids: 'Stuur SMS alerts voor biedingen',
			notifications_product_announcements: 'Productaankondigingen',
			notifications_save: 'Meldingen opslaan',
			orders: 'Orders',
			back: 'Terug',

			// Clock Text
			munt: 'Munt',
			aant_stock: 'Aant/stock',
			rounds: 'Rounde',
			price: 'Prijs',
			min_aant: 'Min. aantal',
			product_naam: 'Product naam',
			aanvoerder: 'Aanvoerder',
			product_id: 'Product ID',
			dimension: 'Dimensie',

			// HubConnectionState
			Disconnected: 'Disconnected',
			Connecting: 'Connecting',
			Connected: 'Connected',
			Reconnecting: 'Reconnecting',
			Disconnecting: 'Disconnecting',

			// Kweker Page texts
			kweker_dashboard: 'Mijn Dashboard',
			kweker_dashboard_sub: 'Overzicht van je profiel en acties',
			kweker_products_description: 'Beheer uw producten en voorraden efficiënt',
			kweker_orders_description: 'Overzicht en beheer van uw bestellingen',
			products_offered: 'Producten aangeboden',
			products_sold: 'Producten verkocht',
			total_earnings: 'Totale verdiensten',
			plants_sold: 'Bloemstelen verkocht',
			active_auctions: 'Actieve veilingen',
			total_products: 'Totaal producten',
			inventory_stock: 'Totaal voorraad',
			total_orders: 'Totaal bestellingen',
			pending_orders: 'Openstaande bestellingen',
			completed_orders: 'Voltooide bestellingen',
			canceled_orders: 'Geannuleerde bestellingen',
			returned_orders: 'Retourede bestellingen',
			recent_orders: 'Recente bestellingen',
			your_products: 'Jouw producten',
			order_update_success: 'Order succesvol bijgewerkt',
			order_update_error: 'Fout bij het bijwerken van de order',
			order_updating: 'Order bijwerken...',
			view_details: 'Bekijk details',
			no_orders: 'Geen bestellingen gevonden',
			no_orders_yet: 'Nog geen bestellingen',
			order_id: 'Order ID',
			order_status: 'Order Status',
			order_datum: 'Order datum',
			total_value: 'Total waarde',
			no_products: 'Geen product gevonden',

			loading_regions: "Regio's laden...",
			failed_load_regions: "Fout bij het laden van regio's",
			regions_loaded: "Regio's succesvol geladen",
			image_upload_error: 'Fout bij het uploaden van de afbeelding',

			// Create Product texts
			product_name: 'Productnaam',
			product_description: 'Productbeschrijving',
			product_dimension: 'Afmeting (bijv. lengte/stamhoogte)',
			enter_product_name: 'Voer productnaam in....',
			enter_product_description: 'Voer productbeschrijving in....',
			minimum_price: 'Prijs per stuk (€)',
			start_price: 'Start Veilingprijs',
			stock_quantity: 'Voorraadhoeveelheid',
			product_image: 'Productafbeelding',
			upload_image: 'Upload afbeelding',
			change_image: 'Wijzig afbeelding',
			choose_image: 'Kies een afbeelding',
			image_upload_instructions: 'Klik om een afbeelding te uploaden (max. 5MB)',
			required_field: 'Verplicht veld',
			invalid_number: 'Ongeldig nummer',
			negative_number: 'Waarde mag niet negatief zijn',
			create_product_button: 'Product aanmaken',
			update_product_button: 'Product bijwerken',
			edit_product: 'Bewerk product',
			create_product: 'Maak product aan',
			delete_product: 'Verwijder product',
			product_creating: 'Product aanmaken...',
			product_updating: 'Product bijwerken...',
			product_created_success: 'Product succesvol aangemaakt',
			product_created_error: 'Fout bij het aanmaken van het product',
			product_updated_success: 'Product succesvol bijgewerkt',
			product_updated_error: 'Fout bij het bijwerken van het product',
			product_deleted_success: 'Product succesvol verwijderd',
			product_deleted_error: 'Fout bij het verwijderen van het product',

			// Required field and error messages
			required: 'vereist',
			email_required_error: 'E-mail vereist',
			email_invalid_error: 'E-mail klopt niet (example@email.com)',
			password_required_error: 'Wachtwoord vereist',

			// Aria labels and alt texts
			alt_flower_picture: 'Bloem afbeelding',
			alt_error_bug_picture: 'Error bug image',
			aria_email: 'Input veld om email in te vullen',
			aria_first_name: 'Input veld om voornaam in te vullen',
			aria_last_name: 'Input veld om achternaam in te vullen',
			aria_password: 'Input veld om wachtwoord in te vullen',
			aria_back_button: 'Knop om terug te gaan',
			aria_login_button: 'Knop om in te loggen',
			aria_forgot_password: 'Wachtwoord vergeten link',
			aria_create_account: 'Account aanmaken link',

			// Common actions
			cancel: 'Annuleren',
			create: 'Aanmaken',
			created: 'Aangemaakt',
			update: 'Bijwerken',
			updated: 'Bijgewerkt',
			delete: 'Verwijderen',
			deleted: 'Verwijderd',
		},
	},
	en: {
		translation: {
			// General texts
			veilingklok: 'Auction Clock',
			growers: 'Growers',
			buyer: 'Buyers',
			language: 'Language',
			services: 'Services',
			flowers: 'Flowers',
			transactions: 'Transactions',
			for: 'for',

			// Account types
			Koper: 'Buyer',
			Kweker: 'Grower',
			Veilingmeester: 'Auctioneer',

			// Auth texts
			login: 'Log in',
			get_Started: 'Get started',
			logout: 'Log out',

			// Auth State messages
			logging_in: 'Logging in...',
			logged_in: 'Logged in successfully',
			creating_account: 'Creating account...',
			logging_out: 'Logging out...',
			account_created: 'Account created successfully',
			account_created_error: 'Account creation failed',
			account_created_error_message: 'An error occurred while creating your account. Please try again later.',
			account_created_error_message_technical: 'An error occurred while creating your account. Please contact support.',
			account_created_error_message_technical_technical: 'An error occurred while creating your account. Please contact support.',

			// Login and register page texts
			login_title: 'Log in',
			welcome_back: 'Welcome back',
			sign_in_message: 'Please sign in to your account',
			forgot_password: 'Forgot password?',
			create_account: 'Create account',
			password: 'Password',
			email: 'Email address',
			address: 'Address',
			postcode: 'Postal code',
			region: 'Region',
			company_name: 'Company name',
			kvk_number: 'Chamber of Commerce number',
			phonenumber: 'Phone number',
			authorisation_code: 'Authorization code',
			country: 'Country',
			step: 'Step',
			of: 'of',
			first_name: 'First name',
			last_name: 'Last name',
			previous: 'Previous',
			next: 'Next',
			login_message: 'Log in?',

			// Home page texts
			what_is_flori_clock: 'What is FloriClock?',
			what_is_flori_clock_description: 'FloriClock is a digital auction platform that connects growers and florists to trade flowers and plants efficiently. Our goal is to simplify and optimize flower and plant trading through a user-friendly online marketplace.',
			how_it_works: 'How does it work?',
			flower_types: 'Flower types',
			flower_types_description: 'Discover a wide range of flower types available on our platform. From roses to tulips, find exactly what you are looking for.',
			contact_us: 'Contact us',
			welcome_title: 'Welcome to FloriClock',
			welcome_description: `Buying and selling flowers and plants has never been easier with FloriClock!
		An innovative platform that connects growers and florists to trade flowers and plants efficiently.`,
			welcome_cta_text: 'Start exploring our platform today. Sign up or log in to access our services.',
			flowers_description: 'Various flower types',
			growers_description: 'Large number of connected growers',
			transactions_description: 'Successful transactions every day',
			what_do_growers: 'List their products and manage their supply',
			veilingmeesters: 'Auctioneers',
			what_do_veilingmeesters: 'Manage auctions and ensure smooth handling',
			what_do_buyer: 'Search and bid on flowers and plants of their choice',
			what_is_veilingklok: 'An advanced system that controls the timing and order of bids during auctions',

			// Buyer dashboard
			koper_dashboard: 'My Dashboard',
			koper_dashboard_sub: 'Overview of your profile and actions',
			koper_supplier: 'Supplier',
			koper_avr: 'AVR no.',
			koper_product: 'Products',
			koper_country: 'Country',
			koper_stems_per_bundle: 'Stems per bundle',
			koper_stock: 'Stock: {{count}} items',
			koper_qty_input_aria: 'Number of stems to buy',
			koper_buy: 'Buy product',
			koper_max_stock: 'Max stock',
			koper_upcoming: 'Upcoming',
			koper_bundle_label: 'bundle',
			koper_footer_about_title: 'About FloriClock',
			koper_footer_about_line1: 'Digital auction for flowers and plants.',
			koper_footer_about_line2: 'Built by students – demo environment.',
			koper_footer_product_title: 'Product',
			koper_footer_live: 'Live auction',
			koper_footer_history: 'Price history',
			koper_footer_favorites: 'Favorites',
			koper_footer_resources_title: 'Resources',
			koper_footer_docs: 'Documentation',
			koper_footer_faq: 'FAQ',
			koper_footer_status: 'Status',
			koper_footer_contact_title: 'Contact',
			koper_footer_support: 'Service & support',
			koper_footer_form: 'Contact form',
			koper_footer_locations: 'Locations',
			refresh: 'Refresh',
			no_products_available: 'No products available',
			koper_product_image_alt: 'Product image',
			koper_upcoming_meta: '{{company}} - {{dimension}}',
			koper_upcoming_badge: 'A1',

			// Grower dashboard
			kweker_welcome: 'Welcome, {{firstName}} {{lastName}}!',
			kweker_desc: 'Welcome to the dashboard! View your products here.',
			kweker_section_products: 'Products',
			kweker_table_product_label: 'Product',
			kweker_table_stock_label: 'Stock',
			kweker_table_price_label: 'Price',
			kweker_table_action_label: 'Action',
			kweker_table_action_view: 'View',
			kweker_table_action_view_aria: 'View product {{name}}',
			kweker_add_product_button: 'Add new product',
			kweker_add_product_button_aria: 'Button to add a new product',
			kweker_add_product_modal_title: 'Add new product',
			kweker_modal_close_aria: 'Close',
			kweker_form_name_label: 'Name',
			kweker_form_name_required: 'Name is required',
			kweker_form_description_label: 'Description',
			kweker_form_description_required: 'Description is required',
			kweker_form_min_price_label: 'Minimum price (EUR)',
			kweker_form_min_price_required: 'Minimum price is required',
			kweker_form_stock_label: 'Quantity',
			kweker_form_stock_required: 'Quantity is required',
			kweker_form_image_label: 'Image (Base64)',
			kweker_form_dimension_label: 'Size',
			kweker_form_submit_busy: 'Saving...',
			kweker_form_submit: 'Add product',
			kweker_form_cancel: 'Cancel',
			kweker_form_create_error: 'Unknown error while creating product',
			kweker_preview_title: 'Product',
			kweker_preview_loading: 'Loading...',
			kweker_preview_error: 'Could not load product.',
			kweker_preview_stock: 'Stock: {{count}}',
			kweker_preview_size: 'Size: {{dimension}}',
			kweker_preview_grower: 'Grower: {{company}}',

			// Grower stats
			kweker_stats_offered: 'Products offered',
			kweker_stats_sold: 'Products sold',
			kweker_stats_total_revenue: 'Total revenue',
			kweker_stats_stems_sold: 'Stems sold',
			kweker_stats_offered_value: '1,500 EUR',
			kweker_stats_sold_value: '50',
			kweker_stats_total_revenue_value: '1,500 EUR',
			kweker_stats_stems_sold_value: '1,000',
			kweker_stats_change: '+0.00%',
			kweker_stats_this_month: 'This month',

			// Auctioneer
			vm_title: 'Auctioneer',
			vm_tab_auction: 'Auction',
			vm_tab_history: 'History',
			vm_section_subtitle: 'Manage the auction and track the products.',
			vm_button_open_auction: 'Open auction',
			vm_button_end_auction: 'End auction',
			vm_button_start_auction: 'Start auction',
			vm_alert_no_products: 'There are no products to auction.',
			vm_alert_open_failed: 'Failed to open auction (see console)',
			vm_alert_min_price_invalid: 'Please enter a valid minimum price first.',
			vm_queue_load_error: 'Failed to load products.',
			vm_empty_no_products: 'No products available.',
			vm_clock_placeholder: 'Clock',
			vm_label_duration_seconds: 'Duration (seconds)',
			vm_label_min_price: 'Minimum price (auctioneer)',
			vm_section_other_products: 'Other products',
			vm_loading_products: 'Loading products...',
			vm_stock_label: 'Stock',
			vm_stock_value: 'Stock: {{count}}',
			vm_max_price_label: 'Maximum price (grower)',
			vm_price_not_set: 'Not set yet',
			vm_history_empty: 'No auction history available yet.',
			vm_history_loading: 'Loading auction history...',
			vm_history_load_error: 'Could not load auction history.',
			vm_history_unknown_date: 'Unknown date',
			vm_history_total_revenue_label: 'Total revenue',
			vm_history_start_label: 'Start',
			vm_history_end_label: 'End',
			vm_history_products_label: 'Products',
			vm_history_revenue_label: 'Revenue',
			vm_history_sold_products_title: 'Sold products',
			vm_history_unknown_buyer: 'Unknown buyer',
			vm_history_piece_count: '{{count}} pieces',
			vm_history_products_count: '{{count}} products',
			vm_history_auction_title: 'Auction {{date}}',
			vm_demo_buyer: 'Demo buyer',

			// Settings & languages
			dashboard: 'Dashboard',
			manage_account: 'Manage account',
			settings: 'Settings',
			settings_account: 'Account',
			settings_privacy: 'Privacy',
			settings_notifications: 'Notifications',
			settings_preferences: 'Preferences',
			settings_preferences_title: 'Preferences',
			settings_preferences_subtitle: 'Customize theme and language for your account.',
			settings_theme_label: 'Display mode',
			settings_theme_aria: 'Toggle between light and dark mode',
			settings_theme_dark: 'Dark mode',
			settings_theme_light: 'Light mode',
			settings_language_label: 'Language',
			settings_account_aria: 'Account tab',
			settings_privacy_aria: 'Privacy tab',
			settings_notifications_aria: 'Notifications tab',
			settings_preferences_aria: 'Preferences tab',
			settings_back_to_dashboard: 'Back to dashboard',
			settings_back_to_dashboard_aria: 'Button to return to dashboard',

			language_dutch: 'Dutch',
			language_english: 'English',
			language_french: 'French',
			language_spanish: 'Spanish',
			language_german: 'German',

			orders: 'Orders',
			back: 'Back',

			// Errors & aria
			go_back_home: 'Go back home',
			something_went_wrong: 'Something went wrong.',
			unexpected_happened: 'An unexpected error occurred. Please try again later.',
			email_required_error: 'Email is required',
			email_invalid_error: 'Invalid email (example@email.com)',
			password_required_error: 'Password is required',
			required: 'required',

			alt_error_bug_picture: 'Error illustration',
			email_aria: 'Email input field',
			first_name_aria: 'First name input field',
			last_name_aria: 'Last name input field',
			password_aria: 'Password input field',
			back_button_aria: 'Back button',
			login_button_aria: 'Login button',
			forgot_password_aria: 'Forgot password link',
			create_account_aria: 'Create account link',
			progress_bar: 'Signup progress: step',
			login_message_aria: 'Return to login link',
		},
	},
	es: {
		translation: {},
	},
	fr: {
		translation: {},
	},
	de: {
		translation: {},
	},
};
i18n
	.use(initReactI18next)
	.init({
		resources,
		lng: 'nl', // if you're using a language detector, do not define the lng option
		fallbackLng: 'nl',
		debug: false,
		interpolation: { escapeValue: false },
	})
	.then(null);

type LocalizationResources = (typeof resources)['nl']; //keyof typeof resources['nl']['translation'];
type LocalizationTexts = keyof (typeof resources)['nl']['translation'];
type SupportedLanguages = keyof typeof resources;
export { useTranslation, LocalizationTexts, LocalizationResources, SupportedLanguages };
