import i18n from 'i18next';
import { initReactI18next, useTranslation } from 'react-i18next';

export const resources = {
	nl: {
		translation: {
			all_statuses: 'Alle statussen',
			all_regions: "Alle regio's",

			// ===== GENERAL TEXTS =====
			welcome: 'Welcome',
			language: 'Taal',
			services: 'Diensten',
			back: 'Terug',
			close: 'Sluiten',
			go_back_home: 'Ga terug naar home',
			cancel: 'Annuleren',
			refresh: 'Vernieuwen',
			view_details: 'Bekijk details',

			// ===== NAVIGATION & MENU =====
			dashboard: 'Dashboard',
			settings: 'Instellingen',
			orders: 'Orders',
			products: 'Producten',
			manage_account: 'Account beheren',
			my_orders: 'Mijn bestellingen',
			browse_flowers: 'Bloemen bekijken',
			auctions: 'Veilingen',
			manage_auction: 'Veilingbeheren',

			// ===== APP OBJECTS =====
			veilingklok: 'Veilingklok',
			growers: 'Kwekers',
			buyer: 'Kopers',
			flowers: 'Bloemen',
			transactions: 'Transacties',
			region_flowers: 'Regio bloemen',

			// ===== DICTIONARY TERMS =====
			welcome_back: 'Welkom terug',
			this_month: 'Deze maand',
			select_region: 'Selecteer regio',
			stock: 'Voorraad',
			status: 'Status',
			items: 'Artikelen',
			is: 'is',
			step: 'Stap',
			of: 'van',
			previous: 'Vorige',
			next: 'Volgende',
			added: 'Toegevoegd',
			for: 'voor',
			date: 'Datum',
			seconds: 'seconden',
			total: 'Totaal',

			// ===== STATUS VALUES =====
			open: 'Open',
			scheduled: 'Ingepland',
			started: 'Gestart',
			paused: 'Gepauzeerd',
			stopped: 'Gestopt',
			ended: 'Beëindigd',
			Processing: 'In behandeling',
			processing: 'In behandeling',
			processed: 'Verwerkt',
			delivered: 'Geleverd',
			cancelled: 'Geannuleerd',
			returned: 'Geretourneerd',

			// ===== ERROR MESSAGES =====
			something_went_wrong: 'Something went wrong.',
			unexpected_happened: 'An unexpected error occurred. Please try again later.',

			// ===== ACCOUNT TYPES =====
			Koper: 'Koper',
			Kweker: 'Kweker',
			Veilingmeester: 'Veilingmeester',

			// ===== AUTH & LOGIN =====
			login: 'Inloggen',
			get_Started: 'Meld je aan',
			logout: 'Uitloggen',
			logging_in: 'Logging in...',
			logged_in: 'Logged in successfully',
			logging_out: 'Logging out...',
			creating_account: 'Creating account...',
			account_created: 'Account created successfully',
			account_created_error: 'Account creation failed',
			account_created_error_message: 'An error occurred while creating your account. Please try again later.',
			account_created_error_message_technical: 'An error occurred while creating your account. Please contact support.',
			account_created_error_message_technical_technical: 'An error occurred while creating your account. Please contact support.',
			login_title: 'Log in',
			sign_in_message: 'Meld u alstublieft aan bij uw account',
			forgot_password: 'Wachtwoord vergeten?',
			create_account: 'Account aanmaken',

			// ===== FORM FIELDS =====
			password: 'Wachtwoord',
			email: 'E-mailadres',
			address: 'Adres',
			postcode: 'Postcode',
			region: 'Regio',
			company_name: 'Bedrijfsnaam',
			kvk_number: 'KVK-Nummer',
			phonenumber: 'Telefoonnummer',
			authorisation_code: 'Autorisatiecode',
			country: 'Land',
			first_name: 'Voornaam',
			last_name: 'Achternaam',

			// ===== HOME PAGE =====
			what_is_flori_clock: 'Wat is FloriClock?',
			what_is_flori_clock_description:
				'FloriClock is een digitaal veilingplatform dat kwekers en bloemisten samenbrengt om bloemen en planten efficiënt te verhandelen. Ons doel is om de veilinghandel in bloemen en planten te vereenvoudigen en te optimaliseren door middel van een gebruiksvriendelijke online marktplaats.',
			how_it_works: 'Hoe werkt het?',
			flower_types: 'Bloemsoorten',
			flower_types_description:
				'Ontdek een breed scala aan bloemsoorten die beschikbaar zijn op ons platform. Van rozen tot tulpen, vind precies wat je zoekt.',
			contact_us: 'Contacteer ons',
			welcome_title: 'Welkom bij FloriClock',
			welcome_description: `Bloemen en planten verkopen en kopen vanop nu nog makkelijker met FloriClock!
			Een innovatief platform dat kwekers en bloemisten samenbrengt om bloemen en planten efficiënt te verhandelen.`,
			welcome_cta_text: `Begin vandaag nog met het ontdekken van ons platform. Meld je aan of log in om toegang te krijgen tot onze diensten.`,
			flowers_description: 'Verschillende bloemsoorten',
			growers_description: 'Groot aantal kwekers aangesloten',
			transactions_description: 'Succesvolle transacties dagelijks',
			what_do_growers: 'Plaatsen van hun producten en beheren van hun aanbod',
			veilingmeesters: 'Veilingmeesters',
			what_do_veilingmeesters: 'Beheren van veilingen en zorgen voor een vlotte afhandeling',
			what_do_buyer: 'Zoeken en bieden op bloemen en planten van hun keuze',
			what_is_veilingklok: 'Een geavanceerd systeem dat de tijd en volgorde van biedingen regelt tijdens veilingen',

			// ===== KOPER DASHBOARD =====
			koper_dashboard: 'Mijn Dashboard',
			koper_dashboard_sub: 'Overzicht van je profiel en acties',
			koper_supplier: 'Aanvoerder',
			koper_avr: 'avr nr',
			koper_country: 'land',
			koper_stems_per_bundle: 'aantal stelen per bos',
			koper_stock: 'Voorraad: {{count}} stuks',
			koper_qty_input_aria: 'Aantal te kopen stelen',
			koper_buy: 'Koop product',
			koper_max_stock: 'Max voorraad',
			koper_bundle_label: 'bos',
			koper_product: 'Product',
			koper_product_image_alt: 'Productafbeelding',
			koper_upcoming: 'Volgende producten',
			koper_upcoming_meta: '{{company}} - {{dimension}}',
			koper_upcoming_badge: 'A1',
			no_products_available: 'Geen producten beschikbaar',
			region_products_txt: 'Hier kunt u de bloemen en planten bekijken die beschikbaar zijn in uw regio.',

			product_naam: 'Productnaam',
			company_naam: 'Bedrijfsnaam',

			// ===== KOPER FOOTER =====
			koper_footer_about_title: 'Over FloriClock',
			koper_footer_about_line1: 'Digitale veiling voor bloemen en planten.',
			koper_footer_about_line2: 'Gebouwd door studenten - demo omgeving.',
			koper_footer_product_title: 'Product',
			koper_footer_live: 'Live veiling',
			koper_footer_history: 'Prijsgeschiedenis',
			koper_footer_favorites: 'Favorieten',
			koper_footer_resources_title: 'Resources',
			koper_footer_docs: 'Documentatie',
			koper_footer_faq: 'Veelgestelde vragen',
			koper_footer_status: 'Status',
			koper_footer_contact_title: 'Contact',
			koper_footer_support: 'Service & support',
			koper_footer_form: 'Contactformulier',
			koper_footer_locations: 'Locaties',

			// ===== KWEKER DASHBOARD =====
			kweker_dashboard: 'Mijn Dashboard',
			kweker_dashboard_sub: 'Overzicht van je profiel en acties',
			kweker_welcome: 'Welkom, {{firstName}} {{lastName}}!',
			kweker_desc: 'Welkom op de dashboard pagina! Bekijk hier uw producten!',
			kweker_products_description: 'Beheer uw producten en voorraden efficiënt',
			confirm_delete_product_warning: 'Weet u zeker dat u dit product wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
			error_fetching_products: 'Er is een fout opgetreden bij het ophalen van de producten.',
			error_deleting_product: 'Er is een fout opgetreden bij het verwijderen van het product.',
			koper_products_description: 'Bekijk hier alle aangeboden bloemen!',
			kweker_orders_description: 'Overzicht en beheer van uw bestellingen',
			kweker_section_products: 'Producten',

			// ===== KWEKER TABLE =====
			kweker_table_product_label: 'Product',
			kweker_table_stock_label: 'Voorraad',
			kweker_table_price_label: 'Prijs',
			kweker_table_action_label: 'Actie',
			kweker_table_action_view: 'Bekijk',
			kweker_table_action_view_aria: 'Bekijk product {{name}}',

			// ===== KWEKER PRODUCT FORM =====
			kweker_add_product_button: 'Voeg nieuw product toe',
			kweker_add_product_button_aria: 'Knop om nieuw product toe te voegen',
			kweker_add_product_modal_title: 'Nieuw product toevoegen',
			kweker_modal_close_aria: 'Sluiten',
			kweker_form_name_label: 'Naam',
			kweker_form_name_required: 'Naam is verplicht',
			kweker_form_description_label: 'Beschrijving',
			kweker_form_description_required: 'Beschrijving is verplicht',
			kweker_form_min_price_label: 'Minimum prijs (EUR)',
			kweker_form_min_price_required: 'Minimum prijs is verplicht',
			kweker_form_stock_label: 'Aantal',
			kweker_form_stock_required: 'Aantal is verplicht',
			kweker_form_image_label: 'Afbeelding (Base64)',
			kweker_form_dimension_label: 'Maat',
			kweker_form_submit_busy: 'Bezig...',
			kweker_form_submit: 'Voeg nieuw product toe',
			kweker_form_cancel: 'Annuleren',
			kweker_form_create_error: 'Onbekende fout bij het aanmaken van product',

			// ===== KWEKER PREVIEW =====
			kweker_preview_title: 'Product',
			kweker_preview_loading: 'Bezig met laden...',
			kweker_preview_error: 'Kon het product niet laden.',
			kweker_preview_stock: 'Voorraad: {{count}}',
			kweker_preview_size: 'Maat: {{dimension}}',
			kweker_preview_grower: 'Kweker: {{company}}',

			// ===== KWEKER STATS =====
			kweker_stats_offered: 'Producten aangeboden',
			kweker_stats_sold: 'Producten verkocht',
			kweker_stats_total_revenue: 'Totale omzet',
			kweker_stats_stems_sold: 'Bloemstelen verkocht',
			kweker_stats_offered_value: '1,500 EUR',
			kweker_stats_sold_value: '50',
			kweker_stats_total_revenue_value: '1,500 EUR',
			kweker_stats_stems_sold_value: '1,000',
			kweker_stats_change: '+0.00%',
			kweker_stats_this_month: 'Deze maand',
			products_offered: 'Producten aangeboden',
			active_auctions: 'Actieve veilingen',
			total_revenue: 'Totale inkomsten',
			orders_received: 'Orders ontvangen',
			total_products: 'Aantal producten',
			inventory_stock: 'Totale voorraad',

			// ===== KWEKER ORDERS =====
			total_orders: 'Totaal aantal bestellingen',
			pending_orders: 'Openstaande bestellingen',
			completed_orders: 'Voltooide bestellingen',
			canceled_orders: 'Geannuleerde bestellingen',
			returned_orders: 'Retourede bestellingen',
			recent_orders: 'Recente bestellingen',
			your_products: 'Jouw producten',
			order_update_success: 'Order succesvol bijgewerkt',
			order_update_error: 'Fout bij het bijwerken van de order',
			order_updating: 'Order bijwerken...',
			no_orders: 'Geen bestellingen gevonden',
			no_orders_yet: 'Nog geen bestellingen',
			order_id: 'Order ID',
			order_status: 'Order Status',
			order_datum: 'Order datum',
			total_value: 'Total waarde',
			no_products: 'Geen product gevonden',
			deliver_adres: 'Afleveradres',
			ordered_products: 'Geplaatste veilingen',
			loading_orders: 'Bestellingen laden...',
			loaded_orders: 'Bestellingen succesvol geladen',
			failed_load_orders: 'Fout bij het laden van bestellingen',
			client_name: 'Klantnaam',
			kweker_name: 'Kwekernaam',
			actions: 'Acties',

			// ===== VEILINGMEESTER DASHBOARD =====
			total_veilingklokken: 'Totaal aantal veilingklokken',
			active_veilingklokken: 'Actieve veilingklokken',
			scheduled_auctions: 'Geplande veilingen',
			available_products: 'Beschikbare producten',
			available_flowers: 'Beschikbare bloemen',
			your_purchases: 'Jouw aankopen',
			vm_title: 'Veilingmeester',
			vm_tab_auction: 'Veiling',
			vm_tab_history: 'History',
			vm_section_subtitle: 'Beheer de veiling en volg de producten.',
			vm_button_open_auction: 'Open veiling',
			vm_button_end_auction: 'Eindig veiling',
			vm_button_start_auction: 'Start veiling',
			vm_alert_no_products: 'Er zijn geen producten om te veilen.',
			vm_alert_open_failed: 'Openen van veiling mislukt (zie console)',
			vm_alert_min_price_invalid: 'Vul eerst een geldige minimumprijs in.',
			vm_queue_load_error: 'Producten ophalen mislukt.',
			vm_empty_no_products: 'Geen producten beschikbaar.',
			vm_clock_placeholder: 'Klok',
			vm_label_duration_seconds: 'Duur (seconden)',
			vm_label_min_price: 'Minimumprijs (veilingmeester)',
			vm_section_other_products: 'Overige producten',
			vm_loading_products: 'Producten laden...',
			vm_stock_label: 'Voorraad',
			vm_stock_value: 'Voorraad: {{count}}',
			vm_max_price_label: 'Maximumprijs (kweker)',
			vm_price_not_set: 'Nog niet gezet',
			vm_demo_buyer: 'Demo koper',

			// ===== VEILINGMEESTER HISTORY =====
			vm_history_empty: 'Nog geen veilinghistorie beschikbaar.',
			vm_history_loading: 'Veilinghistorie laden...',
			vm_history_load_error: 'Kon veilinghistorie niet laden.',
			vm_history_unknown_date: 'Onbekende datum',
			vm_history_total_revenue_label: 'Totale omzet',
			vm_history_start_label: 'Start',
			vm_history_end_label: 'Einde',
			vm_history_products_label: 'Producten',
			vm_history_revenue_label: 'Omzet',
			vm_history_sold_products_title: 'Verkochte producten',
			vm_history_unknown_buyer: 'Onbekende koper',
			vm_history_piece_count: '{{count}} stuks',
			vm_history_products_count: '{{count}} producten',
			vm_history_auction_title: 'Veiling {{date}}',

			// ===== VEILINGMEESTER ARIA LABELS =====
			vm_tab_auction_aria: 'Tabblad veiling',
			vm_tab_history_aria: 'Tabblad historie',
			vm_button_open_auction_aria: 'Knop om veiling te openen',
			vm_button_end_auction_aria: 'Knop om veiling te eindigen',
			vm_button_start_auction_aria: 'Knop om veiling te starten',
			vm_input_duration_aria: 'Invoerveld voor veilingduur in seconden',
			vm_input_min_price_aria: 'Invoerveld voor minimumprijs',
			vm_history_summary_aria: 'Toon details voor veiling op {{date}}',

			// ===== VEILINGMEESTER DEMO DATA =====
			vm_queue_name_1: 'Rode Rozen Premium',
			vm_queue_desc_1: 'Dieprode rozen van topkwaliteit',
			vm_queue_company_1: 'Kwekerij Bloemenhof',
			vm_queue_name_2: 'Witte Lelies',
			vm_queue_desc_2: 'Verse witte lelies, grote knoppen',
			vm_queue_company_2: 'Lelie Centrum BV',
			vm_queue_name_3: 'Zonnebloem XL',
			vm_queue_desc_3: 'Grote zonnebloemen met stevige stelen',
			vm_queue_company_3: 'Zon & Co',
			vm_queue_name_4: 'Tulpen Mix',
			vm_queue_desc_4: 'Mix van voorjaarskleuren, premium selectie',
			vm_queue_company_4: 'Tulipa Holland',
			vm_queue_name_5: 'Orchidee Phalaenopsis',
			vm_queue_desc_5: 'Bloeiend en rijk vertakt',
			vm_queue_company_5: 'Orchid World',

			// ===== VEILINGKLOK MANAGEMENT =====
			select_quantity: 'Aantal selecteren',
			place_bid: 'Bod plaatsen',
			total_price: 'Totale prijs',
			quantity: 'Aantal',
			veilingklok_created: 'Veilingklok succesvol aangemaakt',
			veilingklok_removing_product: 'Product verwijderen van veilingklok...',
			veilingklok_product_removed: 'Product succesvol verwijderd van veilingklok',
			veilingklok_product_remove_error: 'Fout bij het verwijderen van product van veilingklok',
			veilingklok_adding_product: 'Product toevoegen aan veilingklok...',
			veilingklok_product_added: 'Product succesvol toegevoegd aan veilingklok',
			veilingklok_product_add_error: 'Fout bij het toevoegen van product aan veilingklok',
			veilingklok_loading: 'Veilingklokken laden...',
			veilingklok_loaded: 'Veilingklokken succesvol geladen',
			veilingklok_load_error: 'Fout bij het laden van veilingklokken',
			update_auction_clock: 'Veilingklok bijwerken',
			create_auction_clock: 'Veilingklok aanmaken',
			auction_clock_details: 'Veilingklok details',
			total_estimated_value: 'Totaal geschatte waarde',
			no_veilingen_planned: 'Geen veilingen gepland',
			veilingklok_status: 'Veilingklok status',
			scheduledDate: 'Geplande datum',
			totalProducts: 'Totaal producten',
			totalBids: 'Totaal biedingen',
			endedDate: 'Einddatum',
			amount_viewed: 'Aantal bekeken',
			duration_per_bids: 'Duur per bod (seconden)',
			recent_auctionclocks: 'Recente veilingklokken',
			scheduled_for_auction: 'Gepland voor veiling',
			no_veiling_planned: 'Geen veiling gepland',
			set_auction_product_price: 'Stel veilingproductprijs in',
			product_veiling_start_price: 'Veiling startprijs',
			schedule_veilingklok: 'Veilingklok plannen',
			auction_products: 'Veilingklok producten',
			manage_auction_clock: 'Veilingklok beheren',
			join_auction_clock_txt: 'Hier kunt u deelnemen aan de veilingklok die gepland is voor uw regio.',
			manage_product_price_txt: 'Hier kunt u de prijzen van producten beheren die beschikbaar zijn in uw regio.',
			manage_auction_txt: 'Hier kunt u de veilingen beheren die u heeft gepland voor uw regio.',
			manage_veiling_klok_txt: 'Hier kunt u de veilingklokken beheren die u heeft gepland voor uw regio.',
			manage_veiling_klok: 'Veilingklok beheren',
			start_veiling_klok: 'Start Veilingklok',
			stop_veiling_klok: 'Stop Veilingklok',
			pause_veiling_klok: 'Pause Veilingklok',
			resume_veiling_klok: 'Hervat Veilingklok',
			live_views: 'Live weergaven',
			updating_veilingklok: 'Veilingklok bijwerken...',
			veilingklok_updated: 'Veilingklok succesvol bijgewerkt',
			veilingklok_update_error: 'Fout bij het bijwerken van veilingklok',
			starting_product_veiling: 'Veiling van product starten...',
			product_veiling_started: 'Veiling van product succesvol gestart',
			product_veiling_start_error: 'Fout bij het starten van de veiling van het product',
			no_active_veilingklok: 'Geen actieve veilingklok gevonden',
			placing_auction: 'Bid plaatsen...',
			auction_placed: 'Bid succesvol geplaatst',
			auction_place_error: 'Fout bij het plaatsen van de bid',
			kweker_informations: 'Kwekergegevens',
			client_informations: 'Klantgegevens',

			// ===== CLOCK DISPLAY =====
			munt: 'Munt',
			aant_stock: 'Aant/stock',
			rounds: 'Rounde',
			price: 'Prijs',
			min_aant: 'Min. aantal',
			aanvoerder: 'Aanvoerder',
			product_id: 'Product ID',
			dimension: 'Dimensie',

			// ===== SIGNALR HUB CONNECTION STATE =====
			Disconnected: 'Disconnected',
			Connecting: 'Connecting',
			Connected: 'Connected',
			Reconnecting: 'Reconnecting',
			Disconnecting: 'Disconnecting',

			// ===== SETTINGS GENERAL =====
			settings_account: 'Account',
			settings_privacy: 'Privacy',
			settings_notifications: 'Meldingen',
			settings_preferences: 'Voorkeuren',
			settings_preferences_title: 'Voorkeuren',
			settings_preferences_subtitle: 'Pas thema en taal aan voor je account.',
			settings_theme_label: 'Weergavemodus',
			settings_theme_aria: 'Schakel tussen licht en donker thema',
			settings_theme_dark: 'Donkere modus',
			settings_theme_light: 'Lichte modus',
			settings_language_label: 'Taal',
			settings_account_aria: 'Tabblad account',
			settings_privacy_aria: 'Tabblad privacy',
			settings_notifications_aria: 'Tabblad meldingen',
			settings_preferences_aria: 'Tabblad voorkeuren',
			settings_back_to_dashboard: 'Terug naar dashboard',
			settings_back_to_dashboard_aria: 'Knop om terug naar dashboard te gaan',

			// ===== LANGUAGE LABELS =====
			language_dutch: 'Nederlands',
			language_english: 'English',
			language_french: 'Francais',
			language_spanish: 'Espanol',
			language_german: 'Deutsch',

			// ===== ACCOUNT SETTINGS =====
			account_settings_title: 'Account',
			account_settings_subtitle: 'Werk je profielgegevens en wachtwoord bij.',
			account_notice_not_ready: 'Accountgegevens zijn nog niet beschikbaar.',
			account_notice_saving: 'Wijzigingen opslaan...',
			account_notice_required: 'Vul alle verplichte velden in.',
			account_notice_complete_address: 'Vul het volledige adres in.',
			account_notice_no_changes: 'Geen wijzigingen om op te slaan.',
			account_notice_updated: 'Account succesvol bijgewerkt.',
			account_notice_error: 'Er is iets misgegaan bij het opslaan.',
			account_company_name_label: 'Bedrijfsnaam',
			account_company_name_placeholder: 'Bedrijfsnaam',
			account_edit_company_name_aria: 'Bedrijfsnaam bewerken',
			account_first_name_label: 'Voornaam',
			account_first_name_placeholder: 'Voornaam',
			account_last_name_label: 'Achternaam',
			account_last_name_placeholder: 'Achternaam',
			account_email_label: 'E-mailadres',
			account_email_placeholder: 'naam@example.com',
			account_edit_email_aria: 'E-mailadres bewerken',
			account_phone_label: 'Telefoonnummer',
			account_phone_placeholder: '+31 6 12345678',
			account_edit_phone_aria: 'Telefoonnummer bewerken',
			account_region_label: 'Regio',
			account_region_placeholder: 'Noord-Holland',
			account_edit_region_aria: 'Regio bewerken',
			account_address_show: 'Adres wijzigen',
			account_address_hide: 'Verberg adres',
			account_street_label: 'Straat',
			account_street_placeholder: 'Straat',
			account_edit_street_aria: 'Adres bewerken',
			account_city_label: 'Plaats',
			account_city_placeholder: 'Plaats',
			account_edit_city_aria: 'Plaats bewerken',
			account_region_state_label: 'Regio',
			account_region_state_placeholder: 'Regio',
			account_edit_region_state_aria: 'Regio bewerken',
			account_postal_code_label: 'Postcode',
			account_postal_code_placeholder: 'Postcode',
			account_edit_postal_aria: 'Postcode bewerken',
			account_country_label: 'Land',
			account_country_placeholder: 'Land',
			account_edit_country_aria: 'Land bewerken',
			account_password_required: 'Wachtwoord (verplicht)',
			account_password_new: 'Nieuw wachtwoord',
			account_password_placeholder: '********',
			account_password_placeholder_locked: 'Klik om wachtwoord te wijzigen',
			account_password_hide: 'Verbergen',
			account_password_show: 'Tonen',
			account_password_cancel_change: 'Wachtwoord wijzigen annuleren',
			account_password_change: 'Wachtwoord wijzigen',
			account_save_busy: 'Opslaan...',
			account_save: 'Wijzigingen opslaan',
			account_save_aria: 'Knop om wijzigingen op te slaan',

			// ===== PRIVACY SETTINGS =====
			privacy_title: 'Privacy',
			privacy_subtitle: 'Beheer hoe je profiel en activiteit worden gedeeld.',
			privacy_toggle_profile: 'Toon mijn profiel aan andere gebruikers',
			privacy_toggle_search: 'Sta zoekmachines toe mijn profiel te indexeren',
			privacy_toggle_status: 'Deel activiteitsstatus',
			privacy_save: 'Privacy bijwerken',

			// ===== NOTIFICATIONS SETTINGS =====
			notifications_title: 'Meldingen',
			notifications_subtitle: 'Kies hoe je updates wilt ontvangen.',
			notifications_email_updates: 'Stuur e-mail over veilingupdates',
			notifications_sms_bids: 'Stuur SMS alerts voor biedingen',
			notifications_product_announcements: 'Productaankondigingen',
			notifications_save: 'Meldingen opslaan',

			// ===== PRODUCT MANAGEMENT =====
			product_name: 'Productnaam',
			product_description: 'Productbeschrijving',
			product_dimension: 'Afmeting (bijv. lengte/stamhoogte)',
			enter_product_name: 'Voer productnaam in....',
			enter_product_description: 'Voer productbeschrijving in....',
			minimum_price: 'Prijs per stuk (€)',
			start_price: 'Start Veilingprijs',
			stock_quantity: 'Voorraadhoeveelheid',
			product_image: 'Productafbeelding',
			upload_image: 'Upload afbeelding',
			change_image: 'Wijzig afbeelding',
			choose_image: 'Kies een afbeelding',
			image_upload_instructions: 'Klik om een afbeelding te uploaden (max. 5MB)',
			image_upload_error: 'Fout bij het uploaden van de afbeelding',
			create_product_button: 'Product aanmaken',
			update_product_button: 'Product bijwerken',
			edit_product: 'Bewerk product',
			create_product: 'Maak product aan',
			delete_product: 'Verwijder product',
			product_creating: 'Product aanmaken...',
			product_updating: 'Product bijwerken...',
			product_created_success: 'Product succesvol aangemaakt',
			product_created_error: 'Fout bij het aanmaken van het product',
			product_updated_success: 'Product succesvol bijgewerkt',
			product_updated_error: 'Fout bij het bijwerken van het product',
			product_deleted_success: 'Product succesvol verwijderd',
			product_deleted_error: 'Fout bij het verwijderen van het product',

			// ===== REGIONS =====
			loading_regions: "Regio's laden...",
			failed_load_regions: "Fout bij het laden van regio's",
			regions_loaded: "Regio's succesvol geladen",

			// ===== FORM VALIDATION =====
			required_field: 'Verplicht veld',
			invalid_number: 'Ongeldig nummer',
			negative_number: 'Waarde mag niet negatief zijn',
			required: 'vereist',
			email_required_error: 'E-mail vereist',
			email_invalid_error: 'E-mail klopt niet (example@email.com)',
			password_required_error: 'Wachtwoord vereist',

			// ===== ARIA LABELS & ALT TEXTS =====
			alt_flower_picture: 'Bloem afbeelding',
			alt_error_bug_picture: 'Error bug image',
			aria_email: 'Input veld om email in te vullen',
			aria_first_name: 'Input veld om voornaam in te vullen',
			aria_last_name: 'Input veld om achternaam in te vullen',
			aria_password: 'Input veld om wachtwoord in te vullen',
			aria_back_button: 'Knop om terug te gaan',
			aria_login_button: 'Knop om in te loggen',
			aria_forgot_password: 'Wachtwoord vergeten link',
			aria_create_account: 'Account aanmaken link',
			aria_loading: 'Laden',
			aria_product_details: 'Productdetails',
			aria_price_history: 'Prijshistorie',
			aria_view_order_details: 'Bekijk orderdetails',
			aria_download_order_pdf: 'Download order PDF',
			aria_filter_all_status: 'Alle statussen',
			aria_filter_more: 'Meer filters',
			aria_increase_quantity: 'Aantal verhogen',
			aria_decrease_quantity: 'Aantal verlagen',
			aria_veiling_stats: 'Veilingstatistieken',
			aria_kweker_dashboard_stats: 'Dashboard statistieken',
			aria_kweker_products_stats: 'Productstatistieken',
			aria_kweker_revenue_chart: 'Omzetgrafiek',
			aria_kweker_orders_stats: 'Orderstatistieken',
			aria_kweker_order_edit: 'Bewerk order',
			aria_kweker_products_actions: 'Productacties',
			aria_kweker_create_product: 'Product aanmaken',
			aria_kweker_products_list: 'Productenlijst',
			aria_product_details_back: 'Terug naar producten',
			aria_product_details_loading: 'Product laden',
			aria_product_details_error: 'Foutmelding product laden',
			aria_meester_stats: 'Veilingmeester statistieken',
			aria_meester_auction_list: 'Veilingklok overzicht',
			aria_meester_auction_details: 'Veilingklok details',
			aria_meester_products_stats: 'Productstatistieken veilingmeester',
			aria_meester_region_products: 'Regionale producten',
			aria_meester_recent_orders: 'Recente orders',
			aria_meester_manage_auction: 'Veiling beheren',
			aria_meester_schedule_auction: 'Veilingklok plannen',
			aria_meester_delete_auction: 'Veilingklok verwijderen',
			aria_meester_products_list: 'Productlijst',
			aria_meester_action_card: 'Acties',
			aria_meester_clock_products: 'Veilingklok producten',
			aria_meester_auction_clock_manage: 'Veilingklok beheer',
			aria_nav_home: 'Ga naar home',
			aria_nav_home_menu: 'Hoofdmenu',
			aria_nav_what_is: 'Ga naar Wat is FloriClock',
			aria_nav_flower_types: 'Ga naar Bloemsoorten',
			aria_nav_how_it_works: 'Ga naar Hoe werkt het',
			aria_nav_contact: 'Ga naar Contact',
			aria_nav_dashboard: 'Ga naar Dashboard',
			aria_nav_products: 'Ga naar Producten',
			aria_nav_orders: 'Ga naar Orders',
			aria_nav_auctions: 'Ga naar Veilingen',
			aria_nav_browse_flowers: 'Ga naar Bloemen bekijken',
			aria_nav_my_orders: 'Ga naar Mijn bestellingen',
			aria_nav_manage_auction: 'Ga naar Veilingen beheren',
			aria_nav_auction_clocks: 'Ga naar Veilingklokken',
			aria_nav_region_flowers: 'Ga naar Regio bloemen',
			aria_home_register: 'Registreren',
			aria_home_login: 'Inloggen',
			aria_home_dashboard: 'Ga naar dashboard',
			aria_home_image_alt: 'Kweker afbeelding',
			aria_what_is_contact: 'Contacteer ons',
			aria_flower_types_cards: 'Bloemsoorten kaarten',
			aria_flower_card_euphorbia: 'Euphorbia plant',
			aria_flower_card_gerbera: 'Gerbera bloem',
			aria_flower_card_petunia: 'Petunia bloem',
			aria_footer_live_auction: 'Live veiling',
			aria_footer_price_history: 'Prijsgeschiedenis',
			aria_footer_favorites: 'Favorieten',
			aria_footer_docs: 'Documentatie',
			aria_footer_faq: 'Veelgestelde vragen',
			aria_footer_status: 'Status',
			aria_footer_support: 'Service en support',
			aria_footer_contact_form: 'Contactformulier',
			aria_footer_locations: 'Locaties',

			// ===== COMMON ACTIONS =====
			create: 'Aanmaken',
			created: 'Aangemaakt',
			update: 'Bijwerken',
			updated: 'Bijgewerkt',
			delete: 'Verwijderen',
			deleted: 'Verwijderd',

			// ===== ERROR CODES =====
			'ACCOUNT.EMAIL_INVALID': 'Het opgegeven e-mailadres is ongeldig.',
			'ACCOUNT.PASSWORD_TOO_WEAK': 'Het wachtwoord is te zwak.',
			'ACCOUNT.ADRESS_MAXIMUM': 'Maximum aantal adressen bereikt.',
			'ACCOUNT.INVALID_ADRESS': 'Het opgegeven adres is ongeldig.',
			'ACCOUNT.CANNOT_REMOVE_PRIMARY_ADRESS': 'Het primaire adres kan niet worden verwijderd.',
			'ACCOUNT.PASSWORD_EMPTY': 'Wachtwoord mag niet leeg zijn.',
			'ACCOUNT.PASSWORD_TOO_SHORT': 'Wachtwoord moet minimaal 8 tekens lang zijn.',
			'ACCOUNT.PASSWORD_MISSING_UPPERCASE': 'Wachtwoord moet minimaal één hoofdletter bevatten.',
			'ACCOUNT.PASSWORD_MISSING_DIGIT': 'Wachtwoord moet minimaal één cijfer bevatten.',
			'ACCOUNT.NOT_FOUND': 'Account niet gevonden.',
			'ACCOUNT.ADDRESS_NOT_FOUND': 'Adres niet gevonden.',
			'ACCOUNT.ALREADY_EXISTS': 'Er bestaat al een account met dit e-mailadres.',
			'ACCOUNT.KVK_ALREADY_EXISTS': 'Dit KVK-nummer is al geregistreerd.',
			'ACCOUNT.CREATION_FAILED': 'Account aanmaken is mislukt.',

			'KLOK.PRODUCT_NOT_IN_KLOK': 'Het product maakt geen deel uit van de veilingklok.',
			'KLOK.INVALID_DURATION': 'De opgegeven duur voor de veilingklok is ongeldig.',
			'KLOK.INVALID_PEAK_VIEW': 'Ongeldige waarde voor kijkersaantal.',
			'KLOK.NOT_AVAILABLE_FOR_UPDATE': 'De veilingklok kan momenteel niet worden bijgewerkt.',
			'KLOK.ALREADY_ENDED': 'De veilingklok is al beëindigd.',
			'KLOK.INVALID_STATUS_TRANSITION': 'Ongeldige statusovergang voor de veilingklok.',
			'KLOK.CANNOT_MODIFY_ENDED_KLOK': 'Een beëindigde veilingklok kan niet worden gewijzigd.',
			'KLOK.INVALID_PRODUCT_INDEX': 'Ongeldige product index.',

			'ORDER.INVALID_ORDER_STATUS': 'Ongeldige orderstatus.',
			'ORDER.ORDER_IS_NOT_OPEN': 'De order is niet open.',
			'ORDER.ORDER_ALREADY_CLOSED': 'De order is al gesloten.',
			'ORDER.INVALID_ORDERED_ITEM': 'Ongeldig item in de bestelling.',
			'ORDER.MIN_ORDER_QUANTITY_ONE': 'Minimale bestelhoeveelheid is één.',
			'ORDER.INVALID_PRODUCT_PRICE': 'Ongeldige productprijs.',
			'ORDER.ORDER_NOT_FOUND': 'Bestelling niet gevonden.',

			'PRODUCT.DOES_NOT_EXIST': 'Product bestaat niet.',
			'PRODUCT.INVALID_PRODUCT_PRICE': 'Ongeldige productprijs.',
			'PRODUCT.INVALID_MINIMUM_PRICE': 'Ongeldige minimumprijs.',
			'PRODUCT.INSUFFICIENT_PRODUCT_STOCK': 'Onvoldoende voorraad beschikbaar.',
			'PRODUCT.NOT_AVAILABLE_FOR_AUCTION': 'Product is niet beschikbaar voor de veiling.',
			'PRODUCT.MINIMUM_PRICE_EXCEEDS_PRICE': 'De minimumprijs mag niet hoger zijn dan de startprijs.',
			'PRODUCT.NEGATIVE_STOCK_VALUE': 'Voorraad mag niet negatief zijn.',
			'PRODUCT.NOT_FOUND': 'Product niet gevonden.',
			'PRODUCT.INSUFFICIENT_STOCK': 'Onvoldoende voorraad.',

			'VEILINGKLOK.NOT_FOUND': 'Veilingklok niet gevonden.',

			'CUSTOM.CANNOT_DELETE_PRODUCT_WITH_ORDERS': 'Kan product niet verwijderen met bestaande bestellingen.',
			'CUSTOM.EXISTING_TRANSACTION': 'Er is al een transactie in behandeling.',
			'CUSTOM.ALREADY_ACTIVE_VEILING_IN_REGION': 'Er is al een actieve veiling in deze regio.',
			'CUSTOM.JWT_CONFIG_MISSING': 'Interne serverfout: JWT configuratie ontbreekt.',
			'CUSTOM.CANNOT_UPDATE_PRODUCT_LINKED_TO_ACTIVE_VEILING_KLOK':
				'Kan product niet bijwerken terwijl het gekoppeld is aan een actieve veilingklok.',
			'CUSTOM.INVALID_OPERATION': 'Ongeldige bewerking.',
			'CUSTOM.INVALID_CREDENTIALS': 'Ongeldige inloggegevens.',
			'CUSTOM.ACCOUNT_SOFT_DELETED': 'Dit account is verwijderd.',
			'CUSTOM.ACCOUNT_LOCKED': 'Account is geblokkeerd vanwege te veel mislukte pogingen.',
			'CUSTOM.VEILING_KLOK_NOT_STARTED': 'De veilingklok is nog niet gestart.',
			'CUSTOM.INVALID_VEILING_KLOK_STATUS': 'Ongeldige status voor de veilingklok.',
			'CUSTOM.INVALID_VEILING_KLOK_PRODUCT_ID': 'Ongeldig product ID voor de veilingklok.',
			'CUSTOM.INVALID_VEILING_KLOK_NO_PRODUCT': 'Geen product geselecteerd voor de veilingklok.',
			'CUSTOM.CANNOT_CHANGE_RUNNING_VEILING_KLOK': 'Kan een actieve veilingklok niet wijzigen.',
			'CUSTOM.CANNOT_DELETE_STARTED_VEILING_KLOK':
				'Kan een gestarte veilingklok niet verwijderen. Alleen geplande veilingen kunnen worden verwijderd.',
			'CUSTOM.INVALID_OPERATION_KLOK_STILL_RUNNING': 'Bewerking niet mogelijk terwijl de klok nog loopt.',
			'CUSTOM.TOKEN_GENERATION_FAILED': 'Fout bij het genereren van een toegangslink.',
			'CUSTOM.UNAUTHORIZED_ACCESS': 'Onvoldoende rechten voor deze actie.',
			'CUSTOM.ACCESS_FORBIDDEN': 'Toegang geweigerd.',
			'CUSTOM.INSUFFICIENT_PERMISSIONS': 'Onvoldoende machtigingen.',
			'CUSTOM.PRODUCT_ALREADY_LINKED_TO_VEILING_KLOK': 'Product is al gekoppeld aan een veilingklok.',
			'CUSTOM.PRODUCT_NOT_LINKED_TO_VEILING_KLOK': 'Product is niet gekoppeld aan de veilingklok.',
			'CUSTOM.PRODUCT_ALREADY_IN_VEILING_KLOK': 'Product bevindt zich al in de veilingklok.',
			'CUSTOM.ACCOUNT_DEACTIVATED': 'Dit account is gedeactiveerd.',
			'VEILINGKLOK.SCHEDULED_TIME_NOT_IN_FUTURE': 'De geplande tijd moet in de toekomst liggen.',
		},
	},
	en: {
		translation: {
			welcome: 'Welcome',
			language: 'Language',
			services: 'Services',
			back: 'Back',
			close: 'Close',
			go_back_home: 'Go back to home',
			cancel: 'Cancel',
			refresh: 'Refresh',
			view_details: 'View details',
			dashboard: 'Dashboard',
			settings: 'Settings',
			orders: 'Orders',
			products: 'Products',
			manage_account: 'Manage account',
			my_orders: 'My orders',
			browse_flowers: 'Browse flowers',
			auctions: 'Auctions',
			manage_auction: 'Manage auction',
			veilingklok: 'Auction clock',
			growers: 'Growers',
			buyer: 'Buyer',
			flowers: 'Flowers',
			transactions: 'Transactions',
			region_flowers: 'Region flowers',
			welcome_back: 'Welcome back',
			this_month: 'This month',
			select_region: 'Select region',
			stock: 'Stock',
			status: 'Status',
			items: 'Items',
			is: 'is',
			step: 'Step',
			of: 'of',
			previous: 'Previous',
			next: 'Next',
			added: 'Added',
			for: 'for',
			date: 'Date',
			seconds: 'seconds',
			total: 'Total',
			open: 'Open',
			scheduled: 'Scheduled',
			started: 'Started',
			paused: 'Paused',
			stopped: 'Stopped',
			ended: 'Ended',
			Processing: 'Processing',
			processing: 'Processing',
			processed: 'Processed',
			delivered: 'Delivered',
			cancelled: 'Cancelled',
			returned: 'Returned',
			something_went_wrong: 'Something went wrong.',
			unexpected_happened: 'An unexpected error occurred. Please try again later.',
			Koper: 'Buyer',
			Kweker: 'Grower',
			Veilingmeester: 'Auction master',
			login: 'Login',
			get_Started: 'Get started',
			logout: 'Logout',
			logging_in: 'Logging in...',
			logged_in: 'Logged in successfully',
			logging_out: 'Logging out...',
			creating_account: 'Creating account...',
			account_created: 'Account created successfully',
			account_created_error: 'Account creation failed',
			account_created_error_message: 'An error occurred while creating your account. Please try again later.',
			account_created_error_message_technical: 'An error occurred while creating your account. Please contact support.',
			account_created_error_message_technical_technical: 'An error occurred while creating your account. Please contact support.',
			login_title: 'Log in',
			sign_in_message: 'Please sign in to your account',
			forgot_password: 'Forgot password?',
			create_account: 'Create account',
			password: 'Password',
			email: 'Email address',
			address: 'Address',
			postcode: 'Postal code',
			region: 'Region',
			company_name: 'Company name',
			kvk_number: 'KVK Number',
			phonenumber: 'Phone number',
			authorisation_code: 'Authorization code',
			country: 'Country',
			first_name: 'First name',
			last_name: 'Last name',
			what_is_flori_clock: 'What is FloriClock?',
			what_is_flori_clock_description:
				'FloriClock is a digital auction platform that brings growers and florists together to efficiently trade flowers and plants. Our goal is to simplify and optimize flower and plant auction trading through a user-friendly online marketplace.',
			how_it_works: 'How does it work?',
			flower_types: 'Flower types',
			flower_types_description:
				"Discover a wide range of flower types available on our platform. From roses to tulips, find exactly what you're looking for.",
			contact_us: 'Contact us',
			welcome_title: 'Welcome to FloriClock',
			welcome_description:
				'Selling and buying flowers and plants is now even easier with FloriClock! An innovative platform that brings growers and florists together to trade flowers and plants efficiently.',
			welcome_cta_text: 'Start discovering our platform today. Sign up or log in to access our services.',
			flowers_description: 'Different flower types',
			growers_description: 'Large number of connected growers',
			transactions_description: 'Successful daily transactions',
			what_do_growers: 'Placing their products and managing their supply',
			veilingmeesters: 'Auction masters',
			what_do_veilingmeesters: 'Managing auctions and ensuring smooth processing',
			what_do_buyer: 'Searching and bidding on flowers and plants of their choice',
			what_is_veilingklok: 'An advanced system that regulates the time and order of bids during auctions',
			koper_dashboard: 'My Dashboard',
			koper_dashboard_sub: 'Overview of your profile and actions',
			koper_supplier: 'Supplier',
			koper_avr: 'avr nr',
			koper_country: 'country',
			koper_stems_per_bundle: 'number of stems per bundle',
			koper_stock: 'Stock: {{count}} pieces',
			koper_qty_input_aria: 'Number of stems to buy',
			koper_buy: 'Buy product',
			koper_max_stock: 'Max stock',
			koper_bundle_label: 'bundle',
			koper_product: 'Product',
			koper_product_image_alt: 'Product image',
			koper_upcoming: 'Upcoming products',
			koper_upcoming_meta: '{{company}} - {{dimension}}',
			koper_upcoming_badge: 'A1',
			no_products_available: 'No products available',
			region_products_txt: 'Here you can view the flowers and plants available in your region.',
			product_naam: 'Product name',
			company_naam: 'Company name',
			koper_footer_about_title: 'About FloriClock',
			koper_footer_about_line1: 'Digital auction for flowers and plants.',
			koper_footer_about_line2: 'Built by students - demo environment.',
			koper_footer_product_title: 'Product',
			koper_footer_live: 'Live auction',
			koper_footer_history: 'Price history',
			koper_footer_favorites: 'Favorites',
			koper_footer_resources_title: 'Resources',
			koper_footer_docs: 'Documentation',
			koper_footer_faq: 'Frequently asked questions',
			koper_footer_status: 'Status',
			koper_footer_contact_title: 'Contact',
			koper_footer_support: 'Service & support',
			koper_footer_form: 'Contact form',
			koper_footer_locations: 'Locations',
			kweker_dashboard: 'My Dashboard',
			kweker_dashboard_sub: 'Overview of your profile and actions',
			kweker_welcome: 'Welcome, {{firstName}} {{lastName}}!',
			kweker_desc: 'Welcome to the dashboard page! View your products here!',
			kweker_products_description: 'Manage your products and stocks efficiently',
			confirm_delete_product_warning: 'Are you sure you want to delete this product? This cannot be undone.',
			error_fetching_products: 'An error occurred while fetching the products.',
			error_deleting_product: 'An error occurred while deleting the product.',
			koper_products_description: 'View all offered flowers here!',
			kweker_orders_description: 'Overview and management of your orders',
			kweker_section_products: 'Products',
			kweker_table_product_label: 'Product',
			kweker_table_stock_label: 'Stock',
			kweker_table_price_label: 'Price',
			kweker_table_action_label: 'Action',
			kweker_table_action_view: 'View',
			kweker_table_action_view_aria: 'View product {{name}}',
			kweker_add_product_button: 'Add new product',
			kweker_add_product_button_aria: 'Button to add new product',
			kweker_add_product_modal_title: 'Add new product',
			kweker_modal_close_aria: 'Close',
			kweker_form_name_label: 'Name',
			kweker_form_name_required: 'Name is required',
			kweker_form_description_label: 'Description',
			kweker_form_description_required: 'Description is required',
			kweker_form_min_price_label: 'Minimum price (EUR)',
			kweker_form_min_price_required: 'Minimum price is required',
			kweker_form_stock_label: 'Quantity',
			kweker_form_stock_required: 'Quantity is required',
			kweker_form_image_label: 'Image (Base64)',
			kweker_form_dimension_label: 'Size',
			kweker_form_submit_busy: 'Processing...',
			kweker_form_submit: 'Add new product',
			kweker_form_cancel: 'Cancel',
			kweker_form_create_error: 'Unknown error creating product',
			kweker_preview_title: 'Product',
			kweker_preview_loading: 'Loading...',
			kweker_preview_error: 'Could not load product.',
			kweker_preview_stock: 'Stock: {{count}}',
			kweker_preview_size: 'Size: {{dimension}}',
			kweker_preview_grower: 'Grower: {{company}}',
			kweker_stats_offered: 'Products offered',
			kweker_stats_sold: 'Products sold',
			kweker_stats_total_revenue: 'Total revenue',
			kweker_stats_stems_sold: 'Flower stems sold',
			kweker_stats_offered_value: '1,500 EUR',
			kweker_stats_sold_value: '50',
			kweker_stats_total_revenue_value: '1,500 EUR',
			kweker_stats_stems_sold_value: '1,000',
			kweker_stats_change: '+0.00%',
			kweker_stats_this_month: 'This month',
			products_offered: 'Products offered',
			active_auctions: 'Active auctions',
			total_revenue: 'Total revenue',
			orders_received: 'Orders received',
			total_products: 'Number of products',
			inventory_stock: 'Total stock',
			total_orders: 'Total number of orders',
			pending_orders: 'Pending orders',
			completed_orders: 'Completed orders',
			canceled_orders: 'Canceled orders',
			returned_orders: 'Returned orders',
			recent_orders: 'Recent orders',
			your_products: 'Your products',
			order_update_success: 'Order updated successfully',
			order_update_error: 'Error updating order',
			order_updating: 'Updating order...',
			no_orders: 'No orders found',
			no_orders_yet: 'No orders yet',
			order_id: 'Order ID',
			order_status: 'Order Status',
			order_datum: 'Order date',
			total_value: 'Total value',
			no_products: 'No product found',
			deliver_adres: 'Delivery address',
			ordered_products: 'Placed auctions',
			loading_orders: 'Loading orders...',
			loaded_orders: 'Orders loaded successfully',
			failed_load_orders: 'Error loading orders',
			client_name: 'Client name',
			kweker_name: 'Grower name',
			actions: 'Actions',
			total_veilingklokken: 'Total number of auction clocks',
			active_veilingklokken: 'Active auction clocks',
			scheduled_auctions: 'Scheduled auctions',
			available_products: 'Available products',
			available_flowers: 'Available flowers',
			your_purchases: 'Your purchases',
			vm_title: 'Auction master',
			vm_tab_auction: 'Auction',
			vm_tab_history: 'History',
			vm_section_subtitle: 'Manage the auction and track the products.',
			vm_button_open_auction: 'Open auction',
			vm_button_end_auction: 'End auction',
			vm_button_start_auction: 'Start auction',
			vm_alert_no_products: 'There are no products to auction.',
			vm_alert_open_failed: 'Opening auction failed (see console)',
			vm_alert_min_price_invalid: 'First enter a valid minimum price.',
			vm_queue_load_error: 'Failed to fetch products.',
			vm_empty_no_products: 'No products available.',
			vm_clock_placeholder: 'Clock',
			vm_label_duration_seconds: 'Duration (seconds)',
			vm_label_min_price: 'Minimum price (auction master)',
			vm_section_other_products: 'Other products',
			vm_loading_products: 'Loading products...',
			vm_stock_label: 'Stock',
			vm_stock_value: 'Stock: {{count}}',
			vm_max_price_label: 'Maximum price (grower)',
			vm_price_not_set: 'Not set yet',
			vm_demo_buyer: 'Demo buyer',
			vm_history_empty: 'No auction history available yet.',
			vm_history_loading: 'Loading auction history...',
			vm_history_load_error: 'Could not load auction history.',
			vm_history_unknown_date: 'Unknown date',
			vm_history_total_revenue_label: 'Total revenue',
			vm_history_start_label: 'Start',
			vm_history_end_label: 'End',
			vm_history_products_label: 'Products',
			vm_history_revenue_label: 'Revenue',
			vm_history_sold_products_title: 'Sold products',
			vm_history_unknown_buyer: 'Unknown buyer',
			vm_history_piece_count: '{{count}} pieces',
			vm_history_products_count: '{{count}} products',
			vm_history_auction_title: 'Auction {{date}}',
			vm_tab_auction_aria: 'Auction tab',
			vm_tab_history_aria: 'History tab',
			vm_button_open_auction_aria: 'Button to open auction',
			vm_button_end_auction_aria: 'Button to end auction',
			vm_button_start_auction_aria: 'Button to start auction',
			vm_input_duration_aria: 'Input field for auction duration in seconds',
			vm_input_min_price_aria: 'Input field for minimum price',
			vm_history_summary_aria: 'Show details for auction on {{date}}',
			vm_queue_name_1: 'Red Roses Premium',
			vm_queue_desc_1: 'Deep red roses of top quality',
			vm_queue_company_1: 'Bloemenhof Nursery',
			vm_queue_name_2: 'White Lilies',
			vm_queue_desc_2: 'Fresh white lilies, large buds',
			vm_queue_company_2: 'Lily Center BV',
			vm_queue_name_3: 'Sunflower XL',
			vm_queue_desc_3: 'Large sunflowers with sturdy stems',
			vm_queue_company_3: 'Sun & Co',
			vm_queue_name_4: 'Tulips Mix',
			vm_queue_desc_4: 'Mix of spring colors, premium selection',
			vm_queue_company_4: 'Tulipa Holland',
			vm_queue_name_5: 'Phalaenopsis Orchid',
			vm_queue_desc_5: 'Blooming and richly branched',
			vm_queue_company_5: 'Orchid World',
			select_quantity: 'Select quantity',
			place_bid: 'Place bid',
			total_price: 'Total price',
			quantity: 'Quantity',
			veilingklok_created: 'Auction clock created successfully',
			veilingklok_removing_product: 'Removing product from auction clock...',
			veilingklok_product_removed: 'Product successfully removed from auction clock',
			veilingklok_product_remove_error: 'Error removing product from auction clock',
			veilingklok_adding_product: 'Adding product to auction clock...',
			veilingklok_product_added: 'Product successfully added to auction clock',
			veilingklok_product_add_error: 'Error adding product to auction clock',
			veilingklok_loading: 'Loading auction clocks...',
			veilingklok_loaded: 'Auction clocks loaded successfully',
			veilingklok_load_error: 'Error loading auction clocks',
			update_auction_clock: 'Update auction clock',
			create_auction_clock: 'Create auction clock',
			auction_clock_details: 'Auction clock details',
			total_estimated_value: 'Total estimated value',
			no_veilingen_planned: 'No auctions planned',
			veilingklok_status: 'Auction clock status',
			scheduledDate: 'Scheduled date',
			totalProducts: 'Total products',
			totalBids: 'Total bids',
			endedDate: 'End date',
			amount_viewed: 'Number of views',
			duration_per_bids: 'Duration per bid (seconds)',
			recent_auctionclocks: 'Recent auction clocks',
			scheduled_for_auction: 'Scheduled for auction',
			no_veiling_planned: 'No auction planned',
			set_auction_product_price: 'Set auction product price',
			product_veiling_start_price: 'Auction start price',
			schedule_veilingklok: 'Schedule auction clock',
			auction_products: 'Auction clock products',
			manage_auction_clock: 'Manage auction clock',
			join_auction_clock_txt: 'Here you can participate in the auction clock scheduled for your region.',
			manage_product_price_txt: 'Here you can manage the prices of products available in your region.',
			manage_auction_txt: 'Here you can manage the auctions you have scheduled for your region.',
			manage_veiling_klok_txt: 'Here you can manage the auction clocks you have scheduled for your region.',
			manage_veiling_klok: 'Manage auction clock',
			start_veiling_klok: 'Start Auction Clock',
			stop_veiling_klok: 'Stop Auction Clock',
			pause_veiling_klok: 'Pause Auction Clock',
			resume_veiling_klok: 'Resume Auction Clock',
			live_views: 'Live views',
			updating_veilingklok: 'Updating auction clock...',
			veilingklok_updated: 'Auction clock updated successfully',
			veilingklok_update_error: 'Error updating auction clock',
			starting_product_veiling: 'Starting product auction...',
			product_veiling_started: 'Product auction started successfully',
			product_veiling_start_error: 'Error starting product auction',
			no_active_veilingklok: 'No active auction clock found',
			placing_auction: 'Placing bid...',
			auction_placed: 'Bid placed successfully',
			auction_place_error: 'Error placing bid',
			kweker_informations: 'Grower information',
			client_informations: 'Client information',
			munt: 'Currency',
			aant_stock: 'Qty/stock',
			rounds: 'Rounds',
			price: 'Price',
			min_aant: 'Min. quantity',
			aanvoerder: 'Supplier',
			product_id: 'Product ID',
			dimension: 'Dimension',
			Disconnected: 'Disconnected',
			Connecting: 'Connecting',
			Connected: 'Connected',
			Reconnecting: 'Reconnecting',
			Disconnecting: 'Disconnecting',
			settings_account: 'Account',
			settings_privacy: 'Privacy',
			settings_notifications: 'Notifications',
			settings_preferences: 'Preferences',
			settings_preferences_title: 'Preferences',
			settings_preferences_subtitle: 'Adjust theme and language for your account.',
			settings_theme_label: 'Display mode',
			settings_theme_aria: 'Switch between light and dark theme',
			settings_theme_dark: 'Dark mode',
			settings_theme_light: 'Light mode',
			settings_language_label: 'Language',
			settings_account_aria: 'Account tab',
			settings_privacy_aria: 'Privacy tab',
			settings_notifications_aria: 'Notifications tab',
			settings_preferences_aria: 'Preferences tab',
			settings_back_to_dashboard: 'Back to dashboard',
			settings_back_to_dashboard_aria: 'Button to go back to dashboard',
			language_dutch: 'Dutch',
			language_english: 'English',
			language_french: 'French',
			language_spanish: 'Spanish',
			language_german: 'German',
			account_settings_title: 'Account',
			account_settings_subtitle: 'Update your profile details and password.',
			account_notice_not_ready: 'Account details are not yet available.',
			account_notice_saving: 'Saving changes...',
			account_notice_required: 'Fill in all required fields.',
			account_notice_complete_address: 'Fill in the complete address.',
			account_notice_no_changes: 'No changes to save.',
			account_notice_updated: 'Account updated successfully.',
			account_notice_error: 'Something went wrong while saving.',
			account_company_name_label: 'Company name',
			account_company_name_placeholder: 'Company name',
			account_edit_company_name_aria: 'Edit company name',
			account_first_name_label: 'First name',
			account_first_name_placeholder: 'First name',
			account_last_name_label: 'Last name',
			account_last_name_placeholder: 'Last name',
			account_email_label: 'Email address',
			account_email_placeholder: 'name@example.com',
			account_edit_email_aria: 'Edit email address',
			account_phone_label: 'Phone number',
			account_phone_placeholder: '+31 6 12345678',
			account_edit_phone_aria: 'Edit phone number',
			account_region_label: 'Region',
			account_region_placeholder: 'North Holland',
			account_edit_region_aria: 'Edit region',
			account_address_show: 'Change address',
			account_address_hide: 'Hide address',
			account_street_label: 'Street',
			account_street_placeholder: 'Street',
			account_edit_street_aria: 'Edit address',
			account_city_label: 'City',
			account_city_placeholder: 'City',
			account_edit_city_aria: 'Edit city',
			account_region_state_label: 'Region',
			account_region_state_placeholder: 'Region',
			account_edit_region_state_aria: 'Edit region',
			account_postal_code_label: 'Postal code',
			account_postal_code_placeholder: 'Postal code',
			account_edit_postal_aria: 'Edit postal code',
			account_country_label: 'Country',
			account_country_placeholder: 'Country',
			account_edit_country_aria: 'Edit country',
			account_password_required: 'Password (required)',
			account_password_new: 'New password',
			account_password_placeholder: '********',
			account_password_placeholder_locked: 'Click to change password',
			account_password_hide: 'Hide',
			account_password_show: 'Show',
			account_password_cancel_change: 'Cancel password change',
			account_password_change: 'Change password',
			account_save_busy: 'Saving...',
			account_save: 'Save changes',
			account_save_aria: 'Button to save changes',
			privacy_title: 'Privacy',
			privacy_subtitle: 'Manage how your profile and activity are shared.',
			privacy_toggle_profile: 'Show my profile to other users',
			privacy_toggle_search: 'Allow search engines to index my profile',
			privacy_toggle_status: 'Share activity status',
			privacy_save: 'Update privacy',
			notifications_title: 'Notifications',
			notifications_subtitle: 'Choose how you want to receive updates.',
			notifications_email_updates: 'Send email about auction updates',
			notifications_sms_bids: 'Send SMS alerts for bids',
			notifications_product_announcements: 'Product announcements',
			notifications_save: 'Save notifications',
			product_name: 'Product name',
			product_description: 'Product description',
			product_dimension: 'Dimension (e.g. length/stem height)',
			enter_product_name: 'Enter product name...',
			enter_product_description: 'Enter product description...',
			minimum_price: 'Price per piece (€)',
			start_price: 'Auction start price',
			stock_quantity: 'Stock quantity',
			product_image: 'Product image',
			upload_image: 'Upload image',
			change_image: 'Change image',
			choose_image: 'Choose an image',
			image_upload_instructions: 'Click to upload an image (max. 5MB)',
			image_upload_error: 'Error uploading image',
			create_product_button: 'Create product',
			update_product_button: 'Update product',
			edit_product: 'Edit product',
			create_product: 'Create product',
			delete_product: 'Delete product',
			product_creating: 'Creating product...',
			product_updating: 'Updating product...',
			product_created_success: 'Product created successfully',
			product_created_error: 'Error creating product',
			product_updated_success: 'Product updated successfully',
			product_updated_error: 'Error updating product',
			product_deleted_success: 'Product deleted successfully',
			product_deleted_error: 'Error deleting product',
			loading_regions: 'Loading regions...',
			failed_load_regions: 'Error loading regions',
			regions_loaded: 'Regions loaded successfully',
			required_field: 'Required field',
			invalid_number: 'Invalid number',
			negative_number: 'Value may not be negative',
			required: 'required',
			email_required_error: 'Email required',
			email_invalid_error: 'Email incorrect (example@email.com)',
			password_required_error: 'Password required',
			alt_flower_picture: 'Flower image',
			alt_error_bug_picture: 'Error bug image',
			aria_email: 'Input field to fill in email',
			aria_first_name: 'Input field to fill in first name',
			aria_last_name: 'Input field to fill in last name',
			aria_password: 'Input field to fill in password',
			aria_back_button: 'Button to go back',
			aria_login_button: 'Button to log in',
			aria_forgot_password: 'Forgot password link',
			aria_create_account: 'Create account link',
			aria_loading: 'Loading',
			aria_product_details: 'Product details',
			aria_price_history: 'Price history',
			aria_view_order_details: 'View order details',
			aria_download_order_pdf: 'Download order PDF',
			aria_filter_all_status: 'All statuses',
			aria_filter_more: 'More filters',
			aria_increase_quantity: 'Increase quantity',
			aria_decrease_quantity: 'Decrease quantity',
			aria_veiling_stats: 'Auction statistics',
			aria_kweker_dashboard_stats: 'Dashboard statistics',
			aria_kweker_products_stats: 'Product statistics',
			aria_kweker_revenue_chart: 'Revenue chart',
			aria_kweker_orders_stats: 'Order statistics',
			aria_kweker_order_edit: 'Edit order',
			aria_kweker_products_actions: 'Product actions',
			aria_kweker_create_product: 'Create product',
			aria_kweker_products_list: 'Products list',
			aria_product_details_back: 'Back to products',
			aria_product_details_loading: 'Loading product',
			aria_product_details_error: 'Product loading error message',
			aria_meester_stats: 'Auction master statistics',
			aria_meester_auction_list: 'Auction clock overview',
			aria_meester_auction_details: 'Auction clock details',
			aria_meester_products_stats: 'Auction master product statistics',
			aria_meester_region_products: 'Regional products',
			aria_meester_recent_orders: 'Recent orders',
			aria_meester_manage_auction: 'Manage auction',
			aria_meester_schedule_auction: 'Schedule auction clock',
			aria_meester_delete_auction: 'Delete auction clock',
			aria_meester_products_list: 'Product list',
			aria_meester_action_card: 'Actions',
			aria_meester_clock_products: 'Auction clock products',
			aria_meester_auction_clock_manage: 'Auction clock management',
			aria_nav_home: 'Go to home',
			aria_nav_home_menu: 'Main menu',
			aria_nav_what_is: 'Go to What is FloriClock',
			aria_nav_flower_types: 'Go to Flower types',
			aria_nav_how_it_works: 'Go to How does it work',
			aria_nav_contact: 'Go to Contact',
			aria_nav_dashboard: 'Go to Dashboard',
			aria_nav_products: 'Go to Products',
			aria_nav_orders: 'Go to Orders',
			aria_nav_auctions: 'Go to Auctions',
			aria_nav_browse_flowers: 'Go to Browse flowers',
			aria_nav_my_orders: 'Go to My orders',
			aria_nav_manage_auction: 'Go to Manage auctions',
			aria_nav_auction_clocks: 'Go to Auction clocks',
			aria_nav_region_flowers: 'Go to Region flowers',
			aria_home_register: 'Register',
			aria_home_login: 'Login',
			aria_home_dashboard: 'Go to dashboard',
			aria_home_image_alt: 'Grower image',
			aria_what_is_contact: 'Contact us',
			aria_flower_types_cards: 'Flower type cards',
			aria_flower_card_euphorbia: 'Euphorbia plant',
			aria_flower_card_gerbera: 'Gerbera flower',
			aria_flower_card_petunia: 'Petunia flower',
			aria_footer_live_auction: 'Live auction',
			aria_footer_price_history: 'Price history',
			aria_footer_favorites: 'Favorites',
			aria_footer_docs: 'Documentation',
			aria_footer_faq: 'Frequently asked questions',
			aria_footer_status: 'Status',
			aria_footer_support: 'Service and support',
			aria_footer_contact_form: 'Contact form',
			aria_footer_locations: 'Locations',
			create: 'Create',
			created: 'Created',
			update: 'Update',
			updated: 'Updated',
			delete: 'Delete',
			deleted: 'Deleted',
			'ACCOUNT.EMAIL_INVALID': 'The specified email address is invalid.',
			'ACCOUNT.PASSWORD_TOO_WEAK': 'The password is too weak.',
			'ACCOUNT.ADRESS_MAXIMUM': 'Maximum number of addresses reached.',
			'ACCOUNT.INVALID_ADRESS': 'The specified address is invalid.',
			'ACCOUNT.CANNOT_REMOVE_PRIMARY_ADRESS': 'The primary address cannot be removed.',
			'ACCOUNT.PASSWORD_EMPTY': 'Password may not be empty.',
			'ACCOUNT.PASSWORD_TOO_SHORT': 'Password must be at least 8 characters long.',
			'ACCOUNT.PASSWORD_MISSING_UPPERCASE': 'Password must contain at least one uppercase letter.',
			'ACCOUNT.PASSWORD_MISSING_DIGIT': 'Password must contain at least one digit.',
			'ACCOUNT.NOT_FOUND': 'Account not found.',
			'ACCOUNT.ADDRESS_NOT_FOUND': 'Address not found.',
			'ACCOUNT.ALREADY_EXISTS': 'An account with this email address already exists.',
			'ACCOUNT.KVK_ALREADY_EXISTS': 'This KVK number is already registered.',
			'ACCOUNT.CREATION_FAILED': 'Account creation failed.',
			'KLOK.PRODUCT_NOT_IN_KLOK': 'The product is not part of the auction clock.',
			'KLOK.INVALID_DURATION': 'The specified duration for the auction clock is invalid.',
			'KLOK.INVALID_PEAK_VIEW': 'Invalid value for viewer count.',
			'KLOK.NOT_AVAILABLE_FOR_UPDATE': 'The auction clock cannot be updated at this time.',
			'KLOK.ALREADY_ENDED': 'The auction clock has already ended.',
			'KLOK.INVALID_STATUS_TRANSITION': 'Invalid status transition for the auction clock.',
			'KLOK.CANNOT_MODIFY_ENDED_KLOK': 'A completed auction clock cannot be modified.',
			'KLOK.INVALID_PRODUCT_INDEX': 'Invalid product index.',
			'ORDER.INVALID_ORDER_STATUS': 'Invalid order status.',
			'ORDER.ORDER_IS_NOT_OPEN': 'The order is not open.',
			'ORDER.ORDER_ALREADY_CLOSED': 'The order is already closed.',
			'ORDER.INVALID_ORDERED_ITEM': 'Invalid item in the order.',
			'ORDER.MIN_ORDER_QUANTITY_ONE': 'Minimum order quantity is one.',
			'ORDER.INVALID_PRODUCT_PRICE': 'Invalid product price.',
			'ORDER.ORDER_NOT_FOUND': 'Order not found.',
			'PRODUCT.DOES_NOT_EXIST': 'Product does not exist.',
			'PRODUCT.INVALID_PRODUCT_PRICE': 'Invalid product price.',
			'PRODUCT.INVALID_MINIMUM_PRICE': 'Invalid minimum price.',
			'PRODUCT.INSUFFICIENT_PRODUCT_STOCK': 'Insufficient stock available.',
			'PRODUCT.NOT_AVAILABLE_FOR_AUCTION': 'Product is not available for auction.',
			'PRODUCT.MINIMUM_PRICE_EXCEEDS_PRICE': 'The minimum price may not exceed the starting price.',
			'PRODUCT.NEGATIVE_STOCK_VALUE': 'Stock may not be negative.',
			'PRODUCT.NOT_FOUND': 'Product not found.',
			'PRODUCT.INSUFFICIENT_STOCK': 'Insufficient stock.',
			'VEILINGKLOK.NOT_FOUND': 'Auction clock not found.',
			'CUSTOM.CANNOT_DELETE_PRODUCT_WITH_ORDERS': 'Cannot delete product with existing orders.',
			'CUSTOM.EXISTING_TRANSACTION': 'There is already a transaction in progress.',
			'CUSTOM.ALREADY_ACTIVE_VEILING_IN_REGION': 'There is already an active auction in this region.',
			'CUSTOM.JWT_CONFIG_MISSING': 'Internal server error: JWT configuration missing.',
			'CUSTOM.CANNOT_UPDATE_PRODUCT_LINKED_TO_ACTIVE_VEILING_KLOK': 'Cannot update product while it is linked to an active auction clock.',
			'CUSTOM.INVALID_OPERATION': 'Invalid operation.',
			'CUSTOM.INVALID_CREDENTIALS': 'Invalid login credentials.',
			'CUSTOM.ACCOUNT_SOFT_DELETED': 'This account has been deleted.',
			'CUSTOM.ACCOUNT_LOCKED': 'Account is locked due to too many failed attempts.',
			'CUSTOM.VEILING_KLOK_NOT_STARTED': 'The auction clock has not started yet.',
			'CUSTOM.INVALID_VEILING_KLOK_STATUS': 'Invalid status for the auction clock.',
			'CUSTOM.INVALID_VEILING_KLOK_PRODUCT_ID': 'Invalid product ID for the auction clock.',
			'CUSTOM.INVALID_VEILING_KLOK_NO_PRODUCT': 'No product selected for the auction clock.',
			'CUSTOM.CANNOT_CHANGE_RUNNING_VEILING_KLOK': 'Cannot change an active auction clock.',
			'CUSTOM.CANNOT_DELETE_STARTED_VEILING_KLOK': 'Cannot delete a started auction clock. Only scheduled auctions can be deleted.',
			'CUSTOM.INVALID_OPERATION_KLOK_STILL_RUNNING': 'Operation not possible while the clock is still running.',
			'CUSTOM.TOKEN_GENERATION_FAILED': 'Error generating an access link.',
			'CUSTOM.UNAUTHORIZED_ACCESS': 'Insufficient rights for this action.',
			'CUSTOM.ACCESS_FORBIDDEN': 'Access denied.',
			'CUSTOM.INSUFFICIENT_PERMISSIONS': 'Insufficient permissions.',
			'CUSTOM.PRODUCT_ALREADY_LINKED_TO_VEILING_KLOK': 'Product is already linked to an auction clock.',
			'CUSTOM.PRODUCT_NOT_LINKED_TO_VEILING_KLOK': 'Product is not linked to the auction clock.',
			'CUSTOM.PRODUCT_ALREADY_IN_VEILING_KLOK': 'Product is already in the auction clock.',
			'CUSTOM.ACCOUNT_DEACTIVATED': 'This account has been deactivated.',
			'VEILINGKLOK.SCHEDULED_TIME_NOT_IN_FUTURE': 'The scheduled time must be in the future.',
		},
	},
	es: {
		translation: {
			welcome: 'Bienvenido',
			language: 'Idioma',
			services: 'Servicios',
			back: 'Atrás',
			close: 'Cerrar',
			go_back_home: 'Volver a inicio',
			cancel: 'Cancelar',
			refresh: 'Actualizar',
			view_details: 'Ver detalles',
			dashboard: 'Panel',
			settings: 'Configuración',
			orders: 'Pedidos',
			products: 'Productos',
			manage_account: 'Gestionar cuenta',
			my_orders: 'Mis pedidos',
			browse_flowers: 'Explorar flores',
			auctions: 'Subastas',
			manage_auction: 'Gestionar subasta',
			veilingklok: 'Reloj de subasta',
			growers: 'Cultivadores',
			buyer: 'Comprador',
			flowers: 'Flores',
			transactions: 'Transacciones',
			region_flowers: 'Flores de la región',
			welcome_back: 'Bienvenido de nuevo',
			this_month: 'Este mes',
			select_region: 'Seleccionar región',
			stock: 'Stock',
			status: 'Estado',
			items: 'Artículos',
			is: 'es',
			step: 'Paso',
			of: 'de',
			previous: 'Anterior',
			next: 'Siguiente',
			added: 'Añadido',
			for: 'para',
			date: 'Fecha',
			seconds: 'segundos',
			total: 'Total',
			open: 'Abierto',
			scheduled: 'Programado',
			started: 'Iniciado',
			paused: 'Pausado',
			stopped: 'Detenido',
			ended: 'Terminado',
			Processing: 'Procesando',
			processing: 'Procesando',
			processed: 'Procesado',
			delivered: 'Entregado',
			cancelled: 'Cancelado',
			returned: 'Devuelto',
			something_went_wrong: 'Algo salió mal.',
			unexpected_happened: 'Ocurrió un error inesperado. Por favor, inténtelo de nuevo más tarde.',
			Koper: 'Comprador',
			Kweker: 'Cultivador',
			Veilingmeester: 'Maestro de subastas',
			login: 'Iniciar sesión',
			get_Started: 'Empezar',
			logout: 'Cerrar sesión',
			logging_in: 'Iniciando sesión...',
			logged_in: 'Sesión iniciada correctamente',
			logging_out: 'Cerrando sesión...',
			creating_account: 'Creando cuenta...',
			account_created: 'Cuenta creada correctamente',
			account_created_error: 'Error al crear la cuenta',
			account_created_error_message: 'Ocurrió un error al crear su cuenta. Por favor, inténtelo de nuevo más tarde.',
			account_created_error_message_technical: 'Ocurrió un error al crear su cuenta. Por favor, contacte con soporte.',
			account_created_error_message_technical_technical: 'Ocurrió un error al crear su cuenta. Por favor, contacte con soporte.',
			login_title: 'Iniciar sesión',
			sign_in_message: 'Por favor, inicie sesión en su cuenta',
			forgot_password: '¿Olvidó su contraseña?',
			create_account: 'Crear cuenta',
			password: 'Contraseña',
			email: 'Correo electrónico',
			address: 'Dirección',
			postcode: 'Código postal',
			region: 'Región',
			company_name: 'Nombre de la empresa',
			kvk_number: 'Número KVK',
			phonenumber: 'Número de teléfono',
			authorisation_code: 'Código de autorización',
			country: 'País',
			first_name: 'Nombre',
			last_name: 'Apellido',
			what_is_flori_clock: '¿Qué es FloriClock?',
			what_is_flori_clock_description:
				'FloriClock es una plataforma de subastas digital que reúne a cultivadores y floristas para comerciar flores y plantas de manera eficiente. Nuestro objetivo es simplificar y optimizar el comercio de subastas de flores y plantas a través de un mercado en línea fácil de usar.',
			how_it_works: '¿Cómo funciona?',
			flower_types: 'Tipos de flores',
			flower_types_description:
				'Descubra una amplia gama de tipos de flores disponibles en nuestra plataforma. Desde rosas hasta tulipanes, encuentre exactamente lo que busca.',
			contact_us: 'Contáctenos',
			welcome_title: 'Bienvenido a FloriClock',
			welcome_description:
				'¡Vender y comprar flores y plantas ahora es aún más fácil con FloriClock! Una plataforma innovadora que reúne a cultivadores y floristas para comerciar flores y plantas de manera eficiente.',
			welcome_cta_text: 'Comience a descubrir nuestra plataforma hoy. Regístrese o inicie sesión para acceder a nuestros servicios.',
			flowers_description: 'Diferentes tipos de flores',
			growers_description: 'Gran número de cultivadores conectados',
			transactions_description: 'Transacciones exitosas diarias',
			what_do_growers: 'Colocación de sus productos y gestión de su oferta',
			veilingmeesters: 'Maestros de subastas',
			what_do_veilingmeesters: 'Gestión de subastas y garantía de un procesamiento fluido',
			what_do_buyer: 'Búsqueda y oferta de flores y plantas de su elección',
			what_is_veilingklok: 'Un sistema avanzado que regula el tiempo y el orden de las ofertas durante las subastas',
			koper_dashboard: 'Mi Panel',
			koper_dashboard_sub: 'Resumen de su perfil y acciones',
			koper_supplier: 'Proveedor',
			koper_avr: 'avr nr',
			koper_country: 'país',
			koper_stems_per_bundle: 'número de tallos por ramo',
			koper_stock: 'Stock: {{count}} piezas',
			koper_qty_input_aria: 'Número de tallos a comprar',
			koper_buy: 'Comprar producto',
			koper_max_stock: 'Stock máximo',
			koper_bundle_label: 'ramo',
			koper_product: 'Producto',
			koper_product_image_alt: 'Imagen del producto',
			koper_upcoming: 'Próximos productos',
			koper_upcoming_meta: '{{company}} - {{dimension}}',
			koper_upcoming_badge: 'A1',
			no_products_available: 'No hay productos disponibles',
			region_products_txt: 'Aquí puede ver las flores y plantas disponibles en su región.',
			product_naam: 'Nombre del producto',
			company_naam: 'Nombre de la empresa',
			koper_footer_about_title: 'Acerca de FloriClock',
			koper_footer_about_line1: 'Subasta digital para flores y plantas.',
			koper_footer_about_line2: 'Construido por estudiantes - entorno de demostración.',
			koper_footer_product_title: 'Producto',
			koper_footer_live: 'Subasta en vivo',
			koper_footer_history: 'Historial de precios',
			koper_footer_favorites: 'Favoritos',
			koper_footer_resources_title: 'Recursos',
			koper_footer_docs: 'Documentación',
			koper_footer_faq: 'Preguntas frecuentes',
			koper_footer_status: 'Estado',
			koper_footer_contact_title: 'Contacto',
			koper_footer_support: 'Servicio y soporte',
			koper_footer_form: 'Formulario de contacto',
			koper_footer_locations: 'Ubicaciones',
			kweker_dashboard: 'Mi Panel',
			kweker_dashboard_sub: 'Resumen de su perfil y acciones',
			kweker_welcome: '¡Bienvenido, {{firstName}} {{lastName}}!',
			kweker_desc: '¡Bienvenido a la página del panel! ¡Vea sus productos aquí!',
			kweker_products_description: 'Gestione sus productos y stocks de manera eficiente',
			confirm_delete_product_warning: '¿Está seguro de que desea eliminar este producto? Esto no se puede deshacer.',
			error_fetching_products: 'Ocurrió un error al obtener los productos.',
			error_deleting_product: 'Ocurrió un error al eliminar el producto.',
			koper_products_description: '¡Vea todas las flores ofrecidas aquí!',
			kweker_orders_description: 'Resumen y gestión de sus pedidos',
			kweker_section_products: 'Productos',
			kweker_table_product_label: 'Producto',
			kweker_table_stock_label: 'Stock',
			kweker_table_price_label: 'Precio',
			kweker_table_action_label: 'Acción',
			kweker_table_action_view: 'Ver',
			kweker_table_action_view_aria: 'Ver producto {{name}}',
			kweker_add_product_button: 'Añadir nuevo producto',
			kweker_add_product_button_aria: 'Botón para añadir nuevo producto',
			kweker_add_product_modal_title: 'Añadir nuevo producto',
			kweker_modal_close_aria: 'Cerrar',
			kweker_form_name_label: 'Nombre',
			kweker_form_name_required: 'El nombre es obligatorio',
			kweker_form_description_label: 'Descripción',
			kweker_form_description_required: 'La descripción es obligatoria',
			kweker_form_min_price_label: 'Precio mínimo (EUR)',
			kweker_form_min_price_required: 'El precio mínimo es obligatorio',
			kweker_form_stock_label: 'Cantidad',
			kweker_form_stock_required: 'La cantidad es obligatoria',
			kweker_form_image_label: 'Imagen (Base64)',
			kweker_form_dimension_label: 'Tamaño',
			kweker_form_submit_busy: 'Procesando...',
			kweker_form_submit: 'Añadir nuevo producto',
			kweker_form_cancel: 'Cancelar',
			kweker_form_create_error: 'Error desconocido al crear producto',
			kweker_preview_title: 'Producto',
			kweker_preview_loading: 'Cargando...',
			kweker_preview_error: 'No se pudo cargar el producto.',
			kweker_preview_stock: 'Stock: {{count}}',
			kweker_preview_size: 'Tamaño: {{dimension}}',
			kweker_preview_grower: 'Cultivador: {{company}}',
			kweker_stats_offered: 'Productos ofrecidos',
			kweker_stats_sold: 'Productos vendidos',
			kweker_stats_total_revenue: 'Ingresos totales',
			kweker_stats_stems_sold: 'Tallos de flores vendidos',
			kweker_stats_offered_value: '1.500 EUR',
			kweker_stats_sold_value: '50',
			kweker_stats_total_revenue_value: '1.500 EUR',
			kweker_stats_stems_sold_value: '1.000',
			kweker_stats_change: '+0,00%',
			kweker_stats_this_month: 'Este mes',
			products_offered: 'Productos ofrecidos',
			active_auctions: 'Subastas activas',
			total_revenue: 'Ingresos totales',
			orders_received: 'Pedidos recibidos',
			total_products: 'Número de productos',
			inventory_stock: 'Stock total',
			total_orders: 'Número total de pedidos',
			pending_orders: 'Pedidos pendientes',
			completed_orders: 'Pedidos completados',
			canceled_orders: 'Pedidos cancelados',
			returned_orders: 'Pedidos devueltos',
			recent_orders: 'Pedidos recientes',
			your_products: 'Sus productos',
			order_update_success: 'Pedido actualizado correctamente',
			order_update_error: 'Error al actualizar el pedido',
			order_updating: 'Actualizando pedido...',
			no_orders: 'No se encontraron pedidos',
			no_orders_yet: 'Aún no hay pedidos',
			order_id: 'ID del pedido',
			order_status: 'Estado del pedido',
			order_datum: 'Fecha del pedido',
			total_value: 'Valor total',
			no_products: 'Producto no encontrado',
			deliver_adres: 'Dirección de entrega',
			ordered_products: 'Subastas colocadas',
			loading_orders: 'Cargando pedidos...',
			loaded_orders: 'Pedidos cargados correctamente',
			failed_load_orders: 'Error al cargar pedidos',
			client_name: 'Nombre del cliente',
			kweker_name: 'Nombre del cultivador',
			actions: 'Acciones',
			total_veilingklokken: 'Número total de relojes de subasta',
			active_veilingklokken: 'Relojes de subasta activos',
			scheduled_auctions: 'Subastas programadas',
			available_products: 'Productos disponibles',
			available_flowers: 'Flores disponibles',
			your_purchases: 'Sus compras',
			vm_title: 'Maestro de subastas',
			vm_tab_auction: 'Subasta',
			vm_tab_history: 'Historial',
			vm_section_subtitle: 'Gestione la subasta y realice un seguimiento de los productos.',
			vm_button_open_auction: 'Abrir subasta',
			vm_button_end_auction: 'Terminar subasta',
			vm_button_start_auction: 'Iniciar subasta',
			vm_alert_no_products: 'No hay productos para subastar.',
			vm_alert_open_failed: 'Error al abrir subasta (ver consola)',
			vm_alert_min_price_invalid: 'Primero introduzca un precio mínimo válido.',
			vm_queue_load_error: 'Error al obtener productos.',
			vm_empty_no_products: 'No hay productos disponibles.',
			vm_clock_placeholder: 'Reloj',
			vm_label_duration_seconds: 'Duración (segundos)',
			vm_label_min_price: 'Precio mínimo (maestro de subastas)',
			vm_section_other_products: 'Otros productos',
			vm_loading_products: 'Cargando productos...',
			vm_stock_label: 'Stock',
			vm_stock_value: 'Stock: {{count}}',
			vm_max_price_label: 'Precio máximo (cultivador)',
			vm_price_not_set: 'Aún no establecido',
			vm_demo_buyer: 'Comprador de demostración',
			vm_history_empty: 'Aún no hay historial de subastas disponible.',
			vm_history_loading: 'Cargando historial de subastas...',
			vm_history_load_error: 'No se pudo cargar el historial de subastas.',
			vm_history_unknown_date: 'Fecha desconocida',
			vm_history_total_revenue_label: 'Ingresos totales',
			vm_history_start_label: 'Inicio',
			vm_history_end_label: 'Fin',
			vm_history_products_label: 'Productos',
			vm_history_revenue_label: 'Ingresos',
			vm_history_sold_products_title: 'Productos vendidos',
			vm_history_unknown_buyer: 'Comprador desconocido',
			vm_history_piece_count: '{{count}} piezas',
			vm_history_products_count: '{{count}} productos',
			vm_history_auction_title: 'Subasta {{date}}',
			vm_tab_auction_aria: 'Pestaña de subasta',
			vm_tab_history_aria: 'Pestaña de historial',
			vm_button_open_auction_aria: 'Botón para abrir subasta',
			vm_button_end_auction_aria: 'Botón para terminar subasta',
			vm_button_start_auction_aria: 'Botón para iniciar subasta',
			vm_input_duration_aria: 'Campo de entrada para duración de subasta en segundos',
			vm_input_min_price_aria: 'Campo de entrada para precio mínimo',
			vm_history_summary_aria: 'Mostrar detalles para subasta en {{date}}',
			vm_queue_name_1: 'Rosas Rojas Premium',
			vm_queue_desc_1: 'Rosas rojo intenso de máxima calidad',
			vm_queue_company_1: 'Vivero Bloemenhof',
			vm_queue_name_2: 'Lirios Blancos',
			vm_queue_desc_2: 'Lirios blancos frescos, capullos grandes',
			vm_queue_company_2: 'Lily Center BV',
			vm_queue_name_3: 'Girasol XL',
			vm_queue_desc_3: 'Girasoles grandes con tallos robustos',
			vm_queue_company_3: 'Sun & Co',
			vm_queue_name_4: 'Mezcla de Tulipanes',
			vm_queue_desc_4: 'Mezcla de colores primaverales, selección premium',
			vm_queue_company_4: 'Tulipa Holland',
			vm_queue_name_5: 'Orquídea Phalaenopsis',
			vm_queue_desc_5: 'Floreciente y muy ramificada',
			vm_queue_company_5: 'Orchid World',
			select_quantity: 'Seleccionar cantidad',
			place_bid: 'Hacer oferta',
			total_price: 'Precio total',
			quantity: 'Cantidad',
			veilingklok_created: 'Reloj de subasta creado correctamente',
			veilingklok_removing_product: 'Eliminando producto del reloj de subasta...',
			veilingklok_product_removed: 'Producto eliminado correctamente del reloj de subasta',
			veilingklok_product_remove_error: 'Error al eliminar producto del reloj de subasta',
			veilingklok_adding_product: 'Añadiendo producto al reloj de subasta...',
			veilingklok_product_added: 'Producto añadido correctamente al reloj de subasta',
			veilingklok_product_add_error: 'Error al añadir producto al reloj de subasta',
			veilingklok_loading: 'Cargando relojes de subasta...',
			veilingklok_loaded: 'Relojes de subasta cargados correctamente',
			veilingklok_load_error: 'Error al cargar relojes de subasta',
			update_auction_clock: 'Actualizar reloj de subasta',
			create_auction_clock: 'Crear reloj de subasta',
			auction_clock_details: 'Detalles del reloj de subasta',
			total_estimated_value: 'Valor estimado total',
			no_veilingen_planned: 'No hay subastas programadas',
			veilingklok_status: 'Estado del reloj de subasta',
			scheduledDate: 'Fecha programada',
			totalProducts: 'Productos totales',
			totalBids: 'Ofertas totales',
			endedDate: 'Fecha de finalización',
			amount_viewed: 'Número de vistas',
			duration_per_bids: 'Duración por oferta (segundos)',
			recent_auctionclocks: 'Relojes de subasta recientes',
			scheduled_for_auction: 'Programado para subasta',
			no_veiling_planned: 'No hay subasta programada',
			set_auction_product_price: 'Establecer precio de producto de subasta',
			product_veiling_start_price: 'Precio inicial de subasta',
			schedule_veilingklok: 'Programar reloj de subasta',
			auction_products: 'Productos del reloj de subasta',
			manage_auction_clock: 'Gestionar reloj de subasta',
			join_auction_clock_txt: 'Aquí puede participar en el reloj de subasta programado para su región.',
			manage_product_price_txt: 'Aquí puede gestionar los precios de los productos disponibles en su región.',
			manage_auction_txt: 'Aquí puede gestionar las subastas que ha programado para su región.',
			manage_veiling_klok_txt: 'Aquí puede gestionar los relojes de subasta que ha programado para su región.',
			manage_veiling_klok: 'Gestionar reloj de subasta',
			start_veiling_klok: 'Iniciar Reloj de Subasta',
			stop_veiling_klok: 'Detener Reloj de Subasta',
			pause_veiling_klok: 'Pausar Reloj de Subasta',
			resume_veiling_klok: 'Reanudar Reloj de Subasta',
			live_views: 'Vistas en vivo',
			updating_veilingklok: 'Actualizando reloj de subasta...',
			veilingklok_updated: 'Reloj de subasta actualizado correctamente',
			veilingklok_update_error: 'Error al actualizar reloj de subasta',
			starting_product_veiling: 'Iniciando subasta de producto...',
			product_veiling_started: 'Subasta de producto iniciada correctamente',
			product_veiling_start_error: 'Error al iniciar la subasta del producto',
			no_active_veilingklok: 'No se encontró reloj de subasta activo',
			placing_auction: 'Realizando oferta...',
			auction_placed: 'Oferta realizada correctamente',
			auction_place_error: 'Error al realizar oferta',
			kweker_informations: 'Información del cultivador',
			client_informations: 'Información del cliente',
			munt: 'Moneda',
			aant_stock: 'Cant/stock',
			rounds: 'Rondas',
			price: 'Precio',
			min_aant: 'Cant. mín.',
			aanvoerder: 'Proveedor',
			product_id: 'ID del producto',
			dimension: 'Dimensión',
			Disconnected: 'Desconectado',
			Connecting: 'Conectando',
			Connected: 'Conectado',
			Reconnecting: 'Reconectando',
			Disconnecting: 'Desconectando',
			settings_account: 'Cuenta',
			settings_privacy: 'Privacidad',
			settings_notifications: 'Notificaciones',
			settings_preferences: 'Preferencias',
			settings_preferences_title: 'Preferencias',
			settings_preferences_subtitle: 'Ajuste el tema y el idioma de su cuenta.',
			settings_theme_label: 'Modo de visualización',
			settings_theme_aria: 'Cambiar entre tema claro y oscuro',
			settings_theme_dark: 'Modo oscuro',
			settings_theme_light: 'Modo claro',
			settings_language_label: 'Idioma',
			settings_account_aria: 'Pestaña de cuenta',
			settings_privacy_aria: 'Pestaña de privacidad',
			settings_notifications_aria: 'Pestaña de notificaciones',
			settings_preferences_aria: 'Pestaña de preferencias',
			settings_back_to_dashboard: 'Volver al panel',
			settings_back_to_dashboard_aria: 'Botón para volver al panel',
			language_dutch: 'Neerlandés',
			language_english: 'Inglés',
			language_french: 'Francés',
			language_spanish: 'Español',
			language_german: 'Alemán',
			account_settings_title: 'Cuenta',
			account_settings_subtitle: 'Actualice los detalles de su perfil y contraseña.',
			account_notice_not_ready: 'Los detalles de la cuenta aún no están disponibles.',
			account_notice_saving: 'Guardando cambios...',
			account_notice_required: 'Complete todos los campos obligatorios.',
			account_notice_complete_address: 'Complete la dirección completa.',
			account_notice_no_changes: 'No hay cambios que guardar.',
			account_notice_updated: 'Cuenta actualizada correctamente.',
			account_notice_error: 'Algo salió mal al guardar.',
			account_company_name_label: 'Nombre de la empresa',
			account_company_name_placeholder: 'Nombre de la empresa',
			account_edit_company_name_aria: 'Editar nombre de la empresa',
			account_first_name_label: 'Nombre',
			account_first_name_placeholder: 'Nombre',
			account_last_name_label: 'Apellido',
			account_last_name_placeholder: 'Apellido',
			account_email_label: 'Correo electrónico',
			account_email_placeholder: 'nombre@ejemplo.com',
			account_edit_email_aria: 'Editar correo electrónico',
			account_phone_label: 'Número de teléfono',
			account_phone_placeholder: '+31 6 12345678',
			account_edit_phone_aria: 'Editar número de teléfono',
			account_region_label: 'Región',
			account_region_placeholder: 'Holanda Septentrional',
			account_edit_region_aria: 'Editar región',
			account_address_show: 'Cambiar dirección',
			account_address_hide: 'Ocultar dirección',
			account_street_label: 'Calle',
			account_street_placeholder: 'Calle',
			account_edit_street_aria: 'Editar dirección',
			account_city_label: 'Ciudad',
			account_city_placeholder: 'Ciudad',
			account_edit_city_aria: 'Editar ciudad',
			account_region_state_label: 'Región',
			account_region_state_placeholder: 'Región',
			account_edit_region_state_aria: 'Editar región',
			account_postal_code_label: 'Código postal',
			account_postal_code_placeholder: 'Código postal',
			account_edit_postal_aria: 'Editar código postal',
			account_country_label: 'País',
			account_country_placeholder: 'País',
			account_edit_country_aria: 'Editar país',
			account_password_required: 'Contraseña (obligatoria)',
			account_password_new: 'Nueva contraseña',
			account_password_placeholder: '********',
			account_password_placeholder_locked: 'Haga clic para cambiar la contraseña',
			account_password_hide: 'Ocultar',
			account_password_show: 'Mostrar',
			account_password_cancel_change: 'Cancelar cambio de contraseña',
			account_password_change: 'Cambiar contraseña',
			account_save_busy: 'Guardando...',
			account_save: 'Guardar cambios',
			account_save_aria: 'Botón para guardar cambios',
			privacy_title: 'Privacidad',
			privacy_subtitle: 'Gestione cómo se comparten su perfil y actividad.',
			privacy_toggle_profile: 'Mostrar mi perfil a otros usuarios',
			privacy_toggle_search: 'Permitir que los motores de búsqueda indexen mi perfil',
			privacy_toggle_status: 'Compartir estado de actividad',
			privacy_save: 'Actualizar privacidad',
			notifications_title: 'Notificaciones',
			notifications_subtitle: 'Elija cómo desea recibir actualizaciones.',
			notifications_email_updates: 'Enviar correo electrónico sobre actualizaciones de subastas',
			notifications_sms_bids: 'Enviar alertas SMS por ofertas',
			notifications_product_announcements: 'Anuncios de productos',
			notifications_save: 'Guardar notificaciones',
			product_name: 'Nombre del producto',
			product_description: 'Descripción del producto',
			product_dimension: 'Dimensión (ej. longitud/altura del tallo)',
			enter_product_name: 'Ingrese nombre del producto...',
			enter_product_description: 'Ingrese descripción del producto...',
			minimum_price: 'Precio por pieza (€)',
			start_price: 'Precio inicial de subasta',
			stock_quantity: 'Cantidad en stock',
			product_image: 'Imagen del producto',
			upload_image: 'Subir imagen',
			change_image: 'Cambiar imagen',
			choose_image: 'Elegir una imagen',
			image_upload_instructions: 'Haga clic para subir una imagen (máx. 5MB)',
			image_upload_error: 'Error al subir imagen',
			create_product_button: 'Crear producto',
			update_product_button: 'Actualizar producto',
			edit_product: 'Editar producto',
			create_product: 'Crear producto',
			delete_product: 'Eliminar producto',
			product_creating: 'Creando producto...',
			product_updating: 'Actualizando producto...',
			product_created_success: 'Producto creado correctamente',
			product_created_error: 'Error al crear producto',
			product_updated_success: 'Producto actualizado correctamente',
			product_updated_error: 'Error al actualizar producto',
			product_deleted_success: 'Producto eliminado correctamente',
			product_deleted_error: 'Error al eliminar producto',
			loading_regions: 'Cargando regiones...',
			failed_load_regions: 'Error al cargar regiones',
			regions_loaded: 'Regiones cargadas correctamente',
			required_field: 'Campo obligatorio',
			invalid_number: 'Número inválido',
			negative_number: 'El valor no puede ser negativo',
			required: 'obligatorio',
			email_required_error: 'Correo electrónico obligatorio',
			email_invalid_error: 'Correo electrónico incorrecto (ejemplo@email.com)',
			password_required_error: 'Contraseña obligatoria',
			alt_flower_picture: 'Imagen de flor',
			alt_error_bug_picture: 'Imagen de error',
			aria_email: 'Campo de entrada para llenar correo electrónico',
			aria_first_name: 'Campo de entrada para llenar nombre',
			aria_last_name: 'Campo de entrada para llenar apellido',
			aria_password: 'Campo de entrada para llenar contraseña',
			aria_back_button: 'Botón para ir atrás',
			aria_login_button: 'Botón para iniciar sesión',
			aria_forgot_password: 'Enlace de contraseña olvidada',
			aria_create_account: 'Enlace para crear cuenta',
			aria_loading: 'Cargando',
			aria_product_details: 'Detalles del producto',
			aria_price_history: 'Historial de precios',
			aria_view_order_details: 'Ver detalles del pedido',
			aria_download_order_pdf: 'Descargar PDF del pedido',
			aria_filter_all_status: 'Todos los estados',
			aria_filter_more: 'Más filtros',
			aria_increase_quantity: 'Aumentar cantidad',
			aria_decrease_quantity: 'Disminuir cantidad',
			aria_veiling_stats: 'Estadísticas de subasta',
			aria_kweker_dashboard_stats: 'Estadísticas del panel',
			aria_kweker_products_stats: 'Estadísticas de productos',
			aria_kweker_revenue_chart: 'Gráfico de ingresos',
			aria_kweker_orders_stats: 'Estadísticas de pedidos',
			aria_kweker_order_edit: 'Editar pedido',
			aria_kweker_products_actions: 'Acciones de producto',
			aria_kweker_create_product: 'Crear producto',
			aria_kweker_products_list: 'Lista de productos',
			aria_product_details_back: 'Volver a productos',
			aria_product_details_loading: 'Cargando producto',
			aria_product_details_error: 'Mensaje de error al cargar producto',
			aria_meester_stats: 'Estadísticas de maestro de subastas',
			aria_meester_auction_list: 'Resumen de reloj de subasta',
			aria_meester_auction_details: 'Detalles del reloj de subasta',
			aria_meester_products_stats: 'Estadísticas de productos de maestro de subastas',
			aria_meester_region_products: 'Productos regionales',
			aria_meester_recent_orders: 'Pedidos recientes',
			aria_meester_manage_auction: 'Gestionar subasta',
			aria_meester_schedule_auction: 'Programar reloj de subasta',
			aria_meester_delete_auction: 'Eliminar reloj de subasta',
			aria_meester_products_list: 'Lista de productos',
			aria_meester_action_card: 'Acciones',
			aria_meester_clock_products: 'Productos del reloj de subasta',
			aria_meester_auction_clock_manage: 'Gestión del reloj de subasta',
			aria_nav_home: 'Ir a inicio',
			aria_nav_home_menu: 'Menú principal',
			aria_nav_what_is: 'Ir a ¿Qué es FloriClock?',
			aria_nav_flower_types: 'Ir a Tipos de flores',
			aria_nav_how_it_works: 'Ir a ¿Cómo funciona?',
			aria_nav_contact: 'Ir a Contacto',
			aria_nav_dashboard: 'Ir al Panel',
			aria_nav_products: 'Ir a Productos',
			aria_nav_orders: 'Ir a Pedidos',
			aria_nav_auctions: 'Ir a Subastas',
			aria_nav_browse_flowers: 'Ir a Explorar flores',
			aria_nav_my_orders: 'Ir a Mis pedidos',
			aria_nav_manage_auction: 'Ir a Gestionar subastas',
			aria_nav_auction_clocks: 'Ir a Relojes de subasta',
			aria_nav_region_flowers: 'Ir a Flores de la región',
			aria_home_register: 'Registrarse',
			aria_home_login: 'Iniciar sesión',
			aria_home_dashboard: 'Ir al panel',
			aria_home_image_alt: 'Imagen de cultivador',
			aria_what_is_contact: 'Contáctenos',
			aria_flower_types_cards: 'Tarjetas de tipos de flores',
			aria_flower_card_euphorbia: 'Planta Euphorbia',
			aria_flower_card_gerbera: 'Flor Gerbera',
			aria_flower_card_petunia: 'Flor Petunia',
			aria_footer_live_auction: 'Subasta en vivo',
			aria_footer_price_history: 'Historial de precios',
			aria_footer_favorites: 'Favoritos',
			aria_footer_docs: 'Documentación',
			aria_footer_faq: 'Preguntas frecuentes',
			aria_footer_status: 'Estado',
			aria_footer_support: 'Servicio y soporte',
			aria_footer_contact_form: 'Formulario de contacto',
			aria_footer_locations: 'Ubicaciones',
			create: 'Crear',
			created: 'Creado',
			update: 'Actualizar',
			updated: 'Actualizado',
			delete: 'Eliminar',
			deleted: 'Eliminado',
			'ACCOUNT.EMAIL_INVALID': 'La dirección de correo electrónico especificada no es válida.',
			'ACCOUNT.PASSWORD_TOO_WEAK': 'La contraseña es demasiado débil.',
			'ACCOUNT.ADRESS_MAXIMUM': 'Se alcanzó el número máximo de direcciones.',
			'ACCOUNT.INVALID_ADRESS': 'La dirección especificada no es válida.',
			'ACCOUNT.CANNOT_REMOVE_PRIMARY_ADRESS': 'No se puede eliminar la dirección principal.',
			'ACCOUNT.PASSWORD_EMPTY': 'La contraseña no puede estar vacía.',
			'ACCOUNT.PASSWORD_TOO_SHORT': 'La contraseña debe tener al menos 8 caracteres.',
			'ACCOUNT.PASSWORD_MISSING_UPPERCASE': 'La contraseña debe contener al menos una letra mayúscula.',
			'ACCOUNT.PASSWORD_MISSING_DIGIT': 'La contraseña debe contener al menos un dígito.',
			'ACCOUNT.NOT_FOUND': 'Cuenta no encontrada.',
			'ACCOUNT.ADDRESS_NOT_FOUND': 'Dirección no encontrada.',
			'ACCOUNT.ALREADY_EXISTS': 'Ya existe una cuenta con esta dirección de correo electrónico.',
			'ACCOUNT.KVK_ALREADY_EXISTS': 'Este número KVK ya está registrado.',
			'ACCOUNT.CREATION_FAILED': 'Error al crear la cuenta.',
			'KLOK.PRODUCT_NOT_IN_KLOK': 'El producto no es parte del reloj de subasta.',
			'KLOK.INVALID_DURATION': 'La duración especificada para el reloj de subasta no es válida.',
			'KLOK.INVALID_PEAK_VIEW': 'Valor no válido para el recuento de espectadores.',
			'KLOK.NOT_AVAILABLE_FOR_UPDATE': 'El reloj de subasta no se puede actualizar en este momento.',
			'KLOK.ALREADY_ENDED': 'El reloj de subasta ya ha terminado.',
			'KLOK.INVALID_STATUS_TRANSITION': 'Transición de estado no válida para el reloj de subasta.',
			'KLOK.CANNOT_MODIFY_ENDED_KLOK': 'Un reloj de subasta completado no se puede modificar.',
			'KLOK.INVALID_PRODUCT_INDEX': 'Índice de producto no válido.',
			'ORDER.INVALID_ORDER_STATUS': 'Estado de pedido no válido.',
			'ORDER.ORDER_IS_NOT_OPEN': 'El pedido no está abierto.',
			'ORDER.ORDER_ALREADY_CLOSED': 'El pedido ya está cerrado.',
			'ORDER.INVALID_ORDERED_ITEM': 'Artículo no válido en el pedido.',
			'ORDER.MIN_ORDER_QUANTITY_ONE': 'La cantidad mínima de pedido es uno.',
			'ORDER.INVALID_PRODUCT_PRICE': 'Precio de producto no válido.',
			'ORDER.ORDER_NOT_FOUND': 'Pedido no encontrado.',
			'PRODUCT.DOES_NOT_EXIST': 'El producto no existe.',
			'PRODUCT.INVALID_PRODUCT_PRICE': 'Precio de producto no válido.',
			'PRODUCT.INVALID_MINIMUM_PRICE': 'Precio mínimo no válido.',
			'PRODUCT.INSUFFICIENT_PRODUCT_STOCK': 'Stock insuficiente disponible.',
			'PRODUCT.NOT_AVAILABLE_FOR_AUCTION': 'El producto no está disponible para subasta.',
			'PRODUCT.MINIMUM_PRICE_EXCEEDS_PRICE': 'El precio mínimo no puede exceder el precio inicial.',
			'PRODUCT.NEGATIVE_STOCK_VALUE': 'El stock no puede ser negativo.',
			'PRODUCT.NOT_FOUND': 'Producto no encontrado.',
			'PRODUCT.INSUFFICIENT_STOCK': 'Stock insuficiente.',
			'VEILINGKLOK.NOT_FOUND': 'Reloj de subasta no encontrado.',
			'CUSTOM.CANNOT_DELETE_PRODUCT_WITH_ORDERS': 'No se puede eliminar el producto con pedidos existentes.',
			'CUSTOM.EXISTING_TRANSACTION': 'Ya hay una transacción en curso.',
			'CUSTOM.ALREADY_ACTIVE_VEILING_IN_REGION': 'Ya hay una subasta activa en esta región.',
			'CUSTOM.JWT_CONFIG_MISSING': 'Error interno del servidor: falta configuración JWT.',
			'CUSTOM.CANNOT_UPDATE_PRODUCT_LINKED_TO_ACTIVE_VEILING_KLOK':
				'No se puede actualizar el producto mientras está vinculado a un reloj de subasta activo.',
			'CUSTOM.INVALID_OPERATION': 'Operación no válida.',
			'CUSTOM.INVALID_CREDENTIALS': 'Credenciales de inicio de sesión no válidas.',
			'CUSTOM.ACCOUNT_SOFT_DELETED': 'Esta cuenta ha sido eliminada.',
			'CUSTOM.ACCOUNT_LOCKED': 'La cuenta está bloqueada debido a demasiados intentos fallidos.',
			'CUSTOM.VEILING_KLOK_NOT_STARTED': 'El reloj de subasta aún no ha comenzado.',
			'CUSTOM.INVALID_VEILING_KLOK_STATUS': 'Estado no válido para el reloj de subasta.',
			'CUSTOM.INVALID_VEILING_KLOK_PRODUCT_ID': 'ID de producto no válido para el reloj de subasta.',
			'CUSTOM.INVALID_VEILING_KLOK_NO_PRODUCT': 'No se seleccionó ningún producto para el reloj de subasta.',
			'CUSTOM.CANNOT_CHANGE_RUNNING_VEILING_KLOK': 'No se puede cambiar un reloj de subasta activo.',
			'CUSTOM.CANNOT_DELETE_STARTED_VEILING_KLOK':
				'No se puede eliminar un reloj de subasta iniciado. Solo se pueden eliminar las subastas programadas.',
			'CUSTOM.INVALID_OPERATION_KLOK_STILL_RUNNING': 'Operación no posible mientras el reloj aún está funcionando.',
			'CUSTOM.TOKEN_GENERATION_FAILED': 'Error al generar un enlace de acceso.',
			'CUSTOM.UNAUTHORIZED_ACCESS': 'Derechos insuficientes para esta acción.',
			'CUSTOM.ACCESS_FORBIDDEN': 'Acceso denegado.',
			'CUSTOM.INSUFFICIENT_PERMISSIONS': 'Permisos insuficientes.',
			'CUSTOM.PRODUCT_ALREADY_LINKED_TO_VEILING_KLOK': 'El producto ya está vinculado a un reloj de subasta.',
			'CUSTOM.PRODUCT_NOT_LINKED_TO_VEILING_KLOK': 'El producto no está vinculado al reloj de subasta.',
			'CUSTOM.PRODUCT_ALREADY_IN_VEILING_KLOK': 'El producto ya está en el reloj de subasta.',
			'CUSTOM.ACCOUNT_DEACTIVATED': 'Esta cuenta ha sido desactivada.',
			'VEILINGKLOK.SCHEDULED_TIME_NOT_IN_FUTURE': 'La hora programada debe estar en el futuro.',
		},
	},
	fr: { translation: {} },
	de: { translation: {} },
};

i18n
	.use(initReactI18next)
	.init({
		resources,
		lng: 'nl', // if you're using a language detector, do not define the lng option
		fallbackLng: 'nl',
		debug: false,
		interpolation: { escapeValue: false },
	})
	.then(null);

type LocalizationResources = (typeof resources)['nl']; //keyof typeof resources['nl']['translation'];
type LocalizationTexts = keyof (typeof resources)['nl']['translation'];
type SupportedLanguages = keyof typeof resources;
export { useTranslation, LocalizationTexts, LocalizationResources, SupportedLanguages };
