import i18n from 'i18next';
import { initReactI18next, useTranslation } from 'react-i18next';

export const resources = {
	nl: {
		translation: {
			// General texts
			welcome: 'Welcome',
			language: 'Taal',
			services: 'Diensten',

			// App Objects
			veilingklok: 'Veilingklok',
			growers: 'Kwekers',
			buyer: 'Kopers',
			flowers: 'Bloemen',
			transactions: 'Transacties',
			dashboard: 'Dashboard',
			settings: 'Instellingen',
			orders: 'Orders',
			products: 'Producten',
			back: 'Terug',
			manage_account: 'Account beheren',
			my_orders: 'Mijn bestellingen',
			browse_flowers: 'Bloemen bekijken',
			auctions: 'Veilingen',
			manage_auction: 'Veilingbeheren',
			region_flowers: 'Regio bloemen',

			// Dictionary terms
			welcome_back: 'Welkom terug',
			this_month: 'Deze maand',
			select_region: 'Selecteer regio',
			stock: 'Voorraad',
			status: 'Status',
			items: 'Artikelen',
			is: 'is',
			step: 'Stap',
			of: 'van',
			close: 'Sluiten',
			go_back_home: 'Ga terug naar home',
			previous: 'Vorige',
			next: 'Volgende',
			added: 'Toegevoegd',
			for: 'voor',
			date: 'Datum',
			seconds: 'seconden',
			total: 'Totaal',
			open: 'Open',
			scheduled: 'Ingepland',
			started: 'Gestart',
			paused: 'Gepauzeerd',
			stopped: 'Gestopt',
			ended: 'Beëindigd',
			Processing: 'In behandeling',
			processing: 'In behandeling',
			processed: 'Verwerkt',
			delivered: 'Geleverd',
			cancelled: 'Geannuleerd',
			returned: 'Geretourneerd',
			something_went_wrong: 'Something went wrong.',
			unexpected_happened: 'An unexpected error occurred. Please try again later.',

			// Account types
			Koper: 'Koper',
			Kweker: 'Kweker',
			Veilingmeester: 'Veilingmeester',

			// Auth State messages
			login: 'Inloggen',
			get_Started: 'Meld je aan',
			logout: 'Uitloggen',
			logging_in: 'Logging in...',
			logged_in: 'Logged in successfully',
			logging_out: 'Logging out...',
			creating_account: 'Creating account...',
			account_created: 'Account created successfully',
			account_created_error: 'Account creation failed',
			account_created_error_message: 'An error occurred while creating your account. Please try again later.',
			account_created_error_message_technical: 'An error occurred while creating your account. Please contact support.',
			account_created_error_message_technical_technical: 'An error occurred while creating your account. Please contact support.',

			//Login and register page texts
			login_title: 'Log in',
			sign_in_message: 'Meld u alstublieft aan bij uw account',
			forgot_password: 'Wachtwoord vergeten?',
			create_account: 'Account aanmaken',
			password: 'Wachtwoord',
			email: 'E-mailadres',
			address: 'Adres',
			postcode: 'Postcode',
			region: 'Regio',
			company_name: 'Bedrijfsnaam',
			kvk_number: 'KVK-Nummer',
			phonenumber: 'Telefoonnummer',
			authorisation_code: 'Autorisatiecode',
			country: 'Land',
			first_name: 'Voornaam',
			last_name: 'Achternaam',

			// Home page Texts
			what_is_flori_clock: 'Wat is FloriClock?',
			what_is_flori_clock_description: 'FloriClock is een digitaal veilingplatform dat kwekers en bloemisten samenbrengt om bloemen en planten efficiënt te verhandelen. Ons doel is om de veilinghandel in bloemen en planten te vereenvoudigen en te optimaliseren door middel van een gebruiksvriendelijke online marktplaats.',
			how_it_works: 'Hoe werkt het?',
			flower_types: 'Bloemsoorten',
			flower_types_description: 'Ontdek een breed scala aan bloemsoorten die beschikbaar zijn op ons platform. Van rozen tot tulpen, vind precies wat je zoekt.',
			contact_us: 'Contacteer ons',
			welcome_title: 'Welkom bij FloriClock',
			welcome_description: `Bloemen en planten verkopen en kopen vanop nu nog makkelijker met FloriClock!
			Een innovatief platform dat kwekers en bloemisten samenbrengt om bloemen en planten efficiënt te verhandelen.`,
			welcome_cta_text: `Begin vandaag nog met het ontdekken van ons platform. Meld je aan of log in om toegang te krijgen tot onze diensten.`,
			flowers_description: 'Verschillende bloemsoorten',
			growers_description: 'Groot aantal kwekers aangesloten',
			transactions_description: 'Succesvolle transacties dagelijks',
			what_do_growers: 'Plaatsen van hun producten en beheren van hun aanbod',
			veilingmeesters: 'Veilingmeesters',
			what_do_veilingmeesters: 'Beheren van veilingen en zorgen voor een vlotte afhandeling',
			what_do_buyer: 'Zoeken en bieden op bloemen en planten van hun keuze',
			what_is_veilingklok: 'Een geavanceerd systeem dat de tijd en volgorde van biedingen regelt tijdens veilingen',

			// Koper Dashboard texts
			koper_dashboard: 'Mijn Dashboard',
			koper_dashboard_sub: 'Overzicht van je profiel en acties',
			koper_supplier: 'Aanvoerder',
			koper_avr: 'avr nr',
			koper_country: 'land',
			koper_stems_per_bundle: 'aantal stelen per bos',
			koper_stock: 'Voorraad: {{count}} stuks',
			koper_qty_input_aria: 'Aantal te kopen stelen',
			koper_buy: 'Koop product',
			koper_max_stock: 'Max voorraad',
			koper_bundle_label: 'bos',
			koper_footer_about_title: 'Over FloriClock',
			koper_footer_about_line1: 'Digitale veiling voor bloemen en planten.',
			koper_footer_about_line2: 'Gebouwd door studenten - demo omgeving.',
			koper_footer_product_title: 'Product',
			koper_footer_live: 'Live veiling',
			koper_footer_history: 'Prijsgeschiedenis',
			koper_footer_favorites: 'Favorieten',
			koper_footer_resources_title: 'Resources',
			koper_footer_docs: 'Documentatie',
			koper_footer_faq: 'Veelgestelde vragen',
			koper_footer_status: 'Status',
			koper_footer_contact_title: 'Contact',
			koper_footer_support: 'Service & support',
			koper_footer_form: 'Contactformulier',
			koper_footer_locations: 'Locaties',
			refresh: 'Vernieuwen',
			no_products_available: 'Geen producten beschikbaar',

			// Veilingmeester Texts
			veilingklok_created: 'Veilingklok succesvol aangemaakt',
			veilingklok_removing_product: 'Product verwijderen van veilingklok...',
			veilingklok_product_removed: 'Product succesvol verwijderd van veilingklok',
			veilingklok_product_remove_error: 'Fout bij het verwijderen van product van veilingklok',
			veilingklok_adding_product: 'Product toevoegen aan veilingklok...',
			veilingklok_product_added: 'Product succesvol toegevoegd aan veilingklok',
			veilingklok_product_add_error: 'Fout bij het toevoegen van product aan veilingklok',
			veilingklok_loading: 'Veilingklokken laden...',
			veilingklok_loaded: 'Veilingklokken succesvol geladen',
			veilingklok_load_error: 'Fout bij het laden van veilingklokken',

			update_auction_clock: 'Veilingklok bijwerken',
			create_auction_clock: 'Veilingklok aanmaken',
			auction_clock_details: 'Veilingklok details',
			total_estimated_value: 'Totaal geschatte waarde',
			no_veilingen_planned: 'Geen veilingen gepland',
			veilingklok_status: 'Veilingklok status',
			scheduledDate: 'Geplande datum',
			totalProducts: 'Totaal producten',
			totalBids: 'Totaal biedingen',
			endedDate: 'Einddatum',
			amount_viewed: 'Aantal bekeken',
			duration_per_bids: 'Duur per bod (seconden)',
			recent_auctionclocks: 'Recente veilingklokken',
			scheduled_for_auction: 'Gepland voor veiling',
			no_veiling_planned: 'Geen veiling gepland',
			set_auction_product_price: 'Stel veilingproductprijs in',
			product_veiling_start_price: 'Veiling startprijs',
			schedule_veilingklok: 'Veilingklok plannen',
			auction_products: 'Veilingklok producten',
			manage_auction_clock: 'Veilingklok beheren',
			manage_product_price_txt: 'Hier kunt u de prijzen van producten beheren die beschikbaar zijn in uw regio.',
			manage_auction_txt: 'Hier kunt u de veilingen beheren die u heeft gepland voor uw regio.',
			manage_veiling_klok_txt: 'Hier kunt u de veilingklokken beheren die u heeft gepland voor uw regio.',
			manage_veiling_klok: 'Veilingklok beheren',
			start_veiling_klok: 'Start Veilingklok',
			stop_veiling_klok: 'Stop Veilingklok',
			pause_veiling_klok: 'Pause Veilingklok',
			resume_veiling_klok: 'Hervat Veilingklok',

			// Clock Text
			munt: 'Munt',
			aant_stock: 'Aant/stock',
			rounds: 'Rounde',
			price: 'Prijs',
			min_aant: 'Min. aantal',
			product_naam: 'Product naam',
			aanvoerder: 'Aanvoerder',
			product_id: 'Product ID',
			dimension: 'Dimensie',

			// Kweker Page texts
			kweker_dashboard: 'Mijn Dashboard',
			kweker_dashboard_sub: 'Overzicht van je profiel en acties',
			kweker_products_description: 'Beheer uw producten en voorraden efficiënt',
			kweker_orders_description: 'Overzicht en beheer van uw bestellingen',
			products_offered: 'Producten aangeboden',
			products_sold: 'Producten verkocht',
			total_earnings: 'Totale verdiensten',
			plants_sold: 'Bloemstelen verkocht',
			active_auctions: 'Actieve veilingen',
			total_products: 'Totaal producten',
			inventory_stock: 'Totaal voorraad',
			total_orders: 'Totaal bestellingen',
			pending_orders: 'Openstaande bestellingen',
			completed_orders: 'Voltooide bestellingen',
			canceled_orders: 'Geannuleerde bestellingen',
			returned_orders: 'Retourede bestellingen',
			recent_orders: 'Recente bestellingen',
			your_products: 'Jouw producten',
			order_update_success: 'Order succesvol bijgewerkt',
			order_update_error: 'Fout bij het bijwerken van de order',
			order_updating: 'Order bijwerken...',
			view_details: 'Bekijk details',
			no_orders: 'Geen bestellingen gevonden',
			no_orders_yet: 'Nog geen bestellingen',
			order_id: 'Order ID',
			order_status: 'Order Status',
			order_datum: 'Order datum',
			total_value: 'Total waarde',
			no_products: 'Geen product gevonden',

			loading_regions: "Regio's laden...",
			failed_load_regions: "Fout bij het laden van regio's",
			regions_loaded: "Regio's succesvol geladen",
			image_upload_error: 'Fout bij het uploaden van de afbeelding',

			// Create Product texts
			product_name: 'Productnaam',
			product_description: 'Productbeschrijving',
			product_dimension: 'Afmeting (bijv. lengte/stamhoogte)',
			enter_product_name: 'Voer productnaam in....',
			enter_product_description: 'Voer productbeschrijving in....',
			minimum_price: 'Prijs per stuk (€)',
			start_price: 'Start Veilingprijs',
			stock_quantity: 'Voorraadhoeveelheid',
			product_image: 'Productafbeelding',
			upload_image: 'Upload afbeelding',
			change_image: 'Wijzig afbeelding',
			choose_image: 'Kies een afbeelding',
			image_upload_instructions: 'Klik om een afbeelding te uploaden (max. 5MB)',
			required_field: 'Verplicht veld',
			invalid_number: 'Ongeldig nummer',
			negative_number: 'Waarde mag niet negatief zijn',
			create_product_button: 'Product aanmaken',
			update_product_button: 'Product bijwerken',
			edit_product: 'Bewerk product',
			create_product: 'Maak product aan',
			delete_product: 'Verwijder product',
			product_creating: 'Product aanmaken...',
			product_updating: 'Product bijwerken...',
			product_created_success: 'Product succesvol aangemaakt',
			product_created_error: 'Fout bij het aanmaken van het product',
			product_updated_success: 'Product succesvol bijgewerkt',
			product_updated_error: 'Fout bij het bijwerken van het product',
			product_deleted_success: 'Product succesvol verwijderd',
			product_deleted_error: 'Fout bij het verwijderen van het product',

			// Required field and error messages
			required: 'vereist',
			email_required_error: 'E-mail vereist',
			email_invalid_error: 'E-mail klopt niet (example@email.com)',
			password_required_error: 'Wachtwoord vereist',

			// Aria labels and alt texts
			alt_flower_picture: 'Bloem afbeelding',
			alt_error_bug_picture: 'Error bug image',
			aria_email: 'Input veld om email in te vullen',
			aria_first_name: 'Input veld om voornaam in te vullen',
			aria_last_name: 'Input veld om achternaam in te vullen',
			aria_password: 'Input veld om wachtwoord in te vullen',
			aria_back_button: 'Knop om terug te gaan',
			aria_login_button: 'Knop om in te loggen',
			aria_forgot_password: 'Wachtwoord vergeten link',
			aria_create_account: 'Account aanmaken link',

			// Common actions
			cancel: 'Annuleren',
			create: 'Aanmaken',
			created: 'Aangemaakt',
			update: 'Bijwerken',
			updated: 'Bijgewerkt',
			delete: 'Verwijderen',
			deleted: 'Verwijderd',
		},
	},
	en: {
		translation: {},
	},
	es: {
		translation: {},
	},
	fr: {
		translation: {},
	},
};
i18n
	.use(initReactI18next)
	.init({
		resources,
		lng: 'nl', // if you're using a language detector, do not define the lng option
		fallbackLng: 'nl',
		debug: false,
		interpolation: { escapeValue: false },
	})
	.then(null);

type LocalizationResources = (typeof resources)['nl']; //keyof typeof resources['nl']['translation'];
type LocalizationTexts = keyof (typeof resources)['nl']['translation'];
type SupportedLanguages = keyof typeof resources;
export { useTranslation, LocalizationTexts, LocalizationResources, SupportedLanguages };
