server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://webappklas1groep2-g2gtftgfgdg3fzcc.germanywestcentral-01.azurewebsites.net;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_set_header Host webappklas1groep2-g2gtftgfgdg3fzcc.germanywestcentral-01.azurewebsites.net;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /hubs/ {
        proxy_pass https://webappklas1groep2-g2gtftgfgdg3fzcc.germanywestcentral-01.azurewebsites.net;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host webappklas1groep2-g2gtftgfgdg3fzcc.germanywestcentral-01.azurewebsites.net;
    }

    location / {
        try_files $uri /index.html;
    }
}
